/* tslint:disable */
/* eslint-disable */
/**
 * NKM PKM Coupon Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CouponCommentVm,
    CouponCommentVmFromJSON,
    CouponCommentVmFromJSONTyped,
    CouponCommentVmToJSON,
    CouponDiscountType,
    CouponDiscountTypeFromJSON,
    CouponDiscountTypeFromJSONTyped,
    CouponDiscountTypeToJSON,
    CouponRank,
    CouponRankFromJSON,
    CouponRankFromJSONTyped,
    CouponRankToJSON,
    CouponState,
    CouponStateFromJSON,
    CouponStateFromJSONTyped,
    CouponStateToJSON,
    CouponType,
    CouponTypeFromJSON,
    CouponTypeFromJSONTyped,
    CouponTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface CouponVm
 */
export interface CouponVm {
    /**
     * 
     * @type {number}
     * @memberof CouponVm
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CouponVm
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CouponVm
     */
    description?: string | null;
    /**
     * 
     * @type {CouponRank}
     * @memberof CouponVm
     */
    rank?: CouponRank;
    /**
     * 
     * @type {CouponType}
     * @memberof CouponVm
     */
    type?: CouponType;
    /**
     * 
     * @type {CouponState}
     * @memberof CouponVm
     */
    state?: CouponState;
    /**
     * 
     * @type {Date}
     * @memberof CouponVm
     */
    startDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CouponVm
     */
    endDate?: Date;
    /**
     * 
     * @type {Date}
     * @memberof CouponVm
     */
    expireDate?: Date;
    /**
     * 
     * @type {number}
     * @memberof CouponVm
     */
    couponCount?: number;
    /**
     * 
     * @type {number}
     * @memberof CouponVm
     */
    minimumShoppingValue?: number;
    /**
     * 
     * @type {CouponDiscountType}
     * @memberof CouponVm
     */
    discountType?: CouponDiscountType;
    /**
     * 
     * @type {number}
     * @memberof CouponVm
     */
    discountValue?: number;
    /**
     * 
     * @type {number}
     * @memberof CouponVm
     */
    categoryId?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof CouponVm
     */
    tags?: Array<number> | null;
    /**
     * 
     * @type {Array<CouponCommentVm>}
     * @memberof CouponVm
     */
    comments?: Array<CouponCommentVm> | null;
    /**
     * 
     * @type {boolean}
     * @memberof CouponVm
     */
    isActive?: boolean;
}

export function CouponVmFromJSON(json: any): CouponVm {
    return CouponVmFromJSONTyped(json, false);
}

export function CouponVmFromJSONTyped(json: any, ignoreDiscriminator: boolean): CouponVm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'rank': !exists(json, 'rank') ? undefined : CouponRankFromJSON(json['rank']),
        'type': !exists(json, 'type') ? undefined : CouponTypeFromJSON(json['type']),
        'state': !exists(json, 'state') ? undefined : CouponStateFromJSON(json['state']),
        'startDate': !exists(json, 'startDate') ? undefined : (new Date(json['startDate'])),
        'endDate': !exists(json, 'endDate') ? undefined : (new Date(json['endDate'])),
        'expireDate': !exists(json, 'expireDate') ? undefined : (new Date(json['expireDate'])),
        'couponCount': !exists(json, 'couponCount') ? undefined : json['couponCount'],
        'minimumShoppingValue': !exists(json, 'minimumShoppingValue') ? undefined : json['minimumShoppingValue'],
        'discountType': !exists(json, 'discountType') ? undefined : CouponDiscountTypeFromJSON(json['discountType']),
        'discountValue': !exists(json, 'discountValue') ? undefined : json['discountValue'],
        'categoryId': !exists(json, 'categoryId') ? undefined : json['categoryId'],
        'tags': !exists(json, 'tags') ? undefined : json['tags'],
        'comments': !exists(json, 'comments') ? undefined : (json['comments'] === null ? null : (json['comments'] as Array<any>).map(CouponCommentVmFromJSON)),
        'isActive': !exists(json, 'isActive') ? undefined : json['isActive'],
    };
}

export function CouponVmToJSON(value?: CouponVm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'description': value.description,
        'rank': CouponRankToJSON(value.rank),
        'type': CouponTypeToJSON(value.type),
        'state': CouponStateToJSON(value.state),
        'startDate': value.startDate === undefined ? undefined : (value.startDate.toISOString()),
        'endDate': value.endDate === undefined ? undefined : (value.endDate.toISOString()),
        'expireDate': value.expireDate === undefined ? undefined : (value.expireDate.toISOString()),
        'couponCount': value.couponCount,
        'minimumShoppingValue': value.minimumShoppingValue,
        'discountType': CouponDiscountTypeToJSON(value.discountType),
        'discountValue': value.discountValue,
        'categoryId': value.categoryId,
        'tags': value.tags,
        'comments': value.comments === undefined ? undefined : (value.comments === null ? null : (value.comments as Array<any>).map(CouponCommentVmToJSON)),
        'isActive': value.isActive,
    };
}


