/* tslint:disable */
/* eslint-disable */
/**
 * NKM PKM Coupon Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CouponUserCodeVm,
    CouponUserCodeVmFromJSON,
    CouponUserCodeVmFromJSONTyped,
    CouponUserCodeVmToJSON,
} from './';

/**
 * 
 * @export
 * @interface CouponUserCodeVmPaginatedResponse
 */
export interface CouponUserCodeVmPaginatedResponse {
    /**
     * 
     * @type {Array<CouponUserCodeVm>}
     * @memberof CouponUserCodeVmPaginatedResponse
     */
    result?: Array<CouponUserCodeVm> | null;
    /**
     * 
     * @type {number}
     * @memberof CouponUserCodeVmPaginatedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof CouponUserCodeVmPaginatedResponse
     */
    from?: number;
    /**
     * 
     * @type {number}
     * @memberof CouponUserCodeVmPaginatedResponse
     */
    to?: number;
    /**
     * 
     * @type {number}
     * @memberof CouponUserCodeVmPaginatedResponse
     */
    size?: number;
}

export function CouponUserCodeVmPaginatedResponseFromJSON(json: any): CouponUserCodeVmPaginatedResponse {
    return CouponUserCodeVmPaginatedResponseFromJSONTyped(json, false);
}

export function CouponUserCodeVmPaginatedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CouponUserCodeVmPaginatedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : (json['result'] === null ? null : (json['result'] as Array<any>).map(CouponUserCodeVmFromJSON)),
        'page': !exists(json, 'page') ? undefined : json['page'],
        'from': !exists(json, 'from') ? undefined : json['from'],
        'to': !exists(json, 'to') ? undefined : json['to'],
        'size': !exists(json, 'size') ? undefined : json['size'],
    };
}

export function CouponUserCodeVmPaginatedResponseToJSON(value?: CouponUserCodeVmPaginatedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result === undefined ? undefined : (value.result === null ? null : (value.result as Array<any>).map(CouponUserCodeVmToJSON)),
        'page': value.page,
        'from': value.from,
        'to': value.to,
        'size': value.size,
    };
}


