/* tslint:disable */
/* eslint-disable */
/**
 * NKM PKM Coupon Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailTemplateSummaryVm
 */
export interface EmailTemplateSummaryVm {
    /**
     * 
     * @type {number}
     * @memberof EmailTemplateSummaryVm
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof EmailTemplateSummaryVm
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EmailTemplateSummaryVm
     */
    modifiedBy?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof EmailTemplateSummaryVm
     */
    modifiedAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof EmailTemplateSummaryVm
     */
    version?: number;
}

export function EmailTemplateSummaryVmFromJSON(json: any): EmailTemplateSummaryVm {
    return EmailTemplateSummaryVmFromJSONTyped(json, false);
}

export function EmailTemplateSummaryVmFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailTemplateSummaryVm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'modifiedBy': !exists(json, 'modifiedBy') ? undefined : json['modifiedBy'],
        'modifiedAt': !exists(json, 'modifiedAt') ? undefined : (new Date(json['modifiedAt'])),
        'version': !exists(json, 'version') ? undefined : json['version'],
    };
}

export function EmailTemplateSummaryVmToJSON(value?: EmailTemplateSummaryVm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'modifiedBy': value.modifiedBy,
        'modifiedAt': value.modifiedAt === undefined ? undefined : (value.modifiedAt.toISOString()),
        'version': value.version,
    };
}


