/* tslint:disable */
/* eslint-disable */
/**
 * NKM PKN Coupon Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OrderByType,
    OrderByTypeFromJSON,
    OrderByTypeFromJSONTyped,
    OrderByTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface GetPaginatedTagCategoryQuery
 */
export interface GetPaginatedTagCategoryQuery {
    /**
     * 
     * @type {string}
     * @memberof GetPaginatedTagCategoryQuery
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof GetPaginatedTagCategoryQuery
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof GetPaginatedTagCategoryQuery
     */
    pageSize?: number;
    /**
     * 
     * @type {string}
     * @memberof GetPaginatedTagCategoryQuery
     */
    orderBy?: string | null;
    /**
     * 
     * @type {OrderByType}
     * @memberof GetPaginatedTagCategoryQuery
     */
    orderByType?: OrderByType;
}

export function GetPaginatedTagCategoryQueryFromJSON(json: any): GetPaginatedTagCategoryQuery {
    return GetPaginatedTagCategoryQueryFromJSONTyped(json, false);
}

export function GetPaginatedTagCategoryQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetPaginatedTagCategoryQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
        'orderBy': !exists(json, 'orderBy') ? undefined : json['orderBy'],
        'orderByType': !exists(json, 'orderByType') ? undefined : OrderByTypeFromJSON(json['orderByType']),
    };
}

export function GetPaginatedTagCategoryQueryToJSON(value?: GetPaginatedTagCategoryQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'page': value.page,
        'pageSize': value.pageSize,
        'orderBy': value.orderBy,
        'orderByType': OrderByTypeToJSON(value.orderByType),
    };
}


