/* tslint:disable */
/* eslint-disable */
/**
 * NKM PKM Coupon Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum MethodAttributes {
    ReuseSlot = 'ReuseSlot',
    ReuseSlot = 'ReuseSlot',
    Private = 'Private',
    FamANDAssem = 'FamANDAssem',
    Assembly = 'Assembly',
    Family = 'Family',
    FamORAssem = 'FamORAssem',
    Public = 'Public',
    MemberAccessMask = 'MemberAccessMask',
    UnmanagedExport = 'UnmanagedExport',
    Static = 'Static',
    Final = 'Final',
    Virtual = 'Virtual',
    HideBySig = 'HideBySig',
    VtableLayoutMask = 'VtableLayoutMask',
    VtableLayoutMask = 'VtableLayoutMask',
    CheckAccessOnOverride = 'CheckAccessOnOverride',
    Abstract = 'Abstract',
    SpecialName = 'SpecialName',
    RTSpecialName = 'RTSpecialName',
    PinvokeImpl = 'PinvokeImpl',
    HasSecurity = 'HasSecurity',
    RequireSecObject = 'RequireSecObject',
    ReservedMask = 'ReservedMask'
}

export function MethodAttributesFromJSON(json: any): MethodAttributes {
    return MethodAttributesFromJSONTyped(json, false);
}

export function MethodAttributesFromJSONTyped(json: any, ignoreDiscriminator: boolean): MethodAttributes {
    return json as MethodAttributes;
}

export function MethodAttributesToJSON(value?: MethodAttributes | null): any {
    return value as any;
}

