/* tslint:disable */
/* eslint-disable */
/**
 * NKM PKM Coupon Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RegisterPartnerContactPersonDto,
    RegisterPartnerContactPersonDtoFromJSON,
    RegisterPartnerContactPersonDtoFromJSONTyped,
    RegisterPartnerContactPersonDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface RegisterPartnerDto
 */
export interface RegisterPartnerDto {
    /**
     * 
     * @type {string}
     * @memberof RegisterPartnerDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterPartnerDto
     */
    registrationNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterPartnerDto
     */
    taxNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterPartnerDto
     */
    bankAccount?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterPartnerDto
     */
    addressStreet?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterPartnerDto
     */
    addressStreetNumber?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterPartnerDto
     */
    mailingAddressStreet?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RegisterPartnerDto
     */
    mailingAddressStreetNumber?: string | null;
    /**
     * 
     * @type {RegisterPartnerContactPersonDto}
     * @memberof RegisterPartnerDto
     */
    contact?: RegisterPartnerContactPersonDto;
}

export function RegisterPartnerDtoFromJSON(json: any): RegisterPartnerDto {
    return RegisterPartnerDtoFromJSONTyped(json, false);
}

export function RegisterPartnerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RegisterPartnerDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'registrationNumber': !exists(json, 'registrationNumber') ? undefined : json['registrationNumber'],
        'taxNumber': !exists(json, 'taxNumber') ? undefined : json['taxNumber'],
        'bankAccount': !exists(json, 'bankAccount') ? undefined : json['bankAccount'],
        'addressStreet': !exists(json, 'addressStreet') ? undefined : json['addressStreet'],
        'addressStreetNumber': !exists(json, 'addressStreetNumber') ? undefined : json['addressStreetNumber'],
        'mailingAddressStreet': !exists(json, 'mailingAddressStreet') ? undefined : json['mailingAddressStreet'],
        'mailingAddressStreetNumber': !exists(json, 'mailingAddressStreetNumber') ? undefined : json['mailingAddressStreetNumber'],
        'contact': !exists(json, 'contact') ? undefined : RegisterPartnerContactPersonDtoFromJSON(json['contact']),
    };
}

export function RegisterPartnerDtoToJSON(value?: RegisterPartnerDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'registrationNumber': value.registrationNumber,
        'taxNumber': value.taxNumber,
        'bankAccount': value.bankAccount,
        'addressStreet': value.addressStreet,
        'addressStreetNumber': value.addressStreetNumber,
        'mailingAddressStreet': value.mailingAddressStreet,
        'mailingAddressStreetNumber': value.mailingAddressStreetNumber,
        'contact': RegisterPartnerContactPersonDtoToJSON(value.contact),
    };
}


