/* tslint:disable */
/* eslint-disable */
/**
 * NKM PKM Coupon Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SiteApiKeyVm
 */
export interface SiteApiKeyVm {
    /**
     * 
     * @type {number}
     * @memberof SiteApiKeyVm
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SiteApiKeyVm
     */
    name?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof SiteApiKeyVm
     */
    expireDate?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof SiteApiKeyVm
     */
    isActive?: boolean;
}

export function SiteApiKeyVmFromJSON(json: any): SiteApiKeyVm {
    return SiteApiKeyVmFromJSONTyped(json, false);
}

export function SiteApiKeyVmFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteApiKeyVm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'expireDate': !exists(json, 'expireDate') ? undefined : (new Date(json['expireDate'])),
        'isActive': !exists(json, 'isActive') ? undefined : json['isActive'],
    };
}

export function SiteApiKeyVmToJSON(value?: SiteApiKeyVm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'expireDate': value.expireDate === undefined ? undefined : (value.expireDate.toISOString()),
        'isActive': value.isActive,
    };
}


