/* tslint:disable */
/* eslint-disable */
/**
 * NKM PKM Coupon Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CouponType,
    CouponTypeFromJSON,
    CouponTypeFromJSONTyped,
    CouponTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface UserCouponVm
 */
export interface UserCouponVm {
    /**
     * 
     * @type {string}
     * @memberof UserCouponVm
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserCouponVm
     */
    description?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof UserCouponVm
     */
    expireDate?: Date;
    /**
     * 
     * @type {CouponType}
     * @memberof UserCouponVm
     */
    type?: CouponType;
    /**
     * 
     * @type {number}
     * @memberof UserCouponVm
     */
    discountValue?: number;
}

export function UserCouponVmFromJSON(json: any): UserCouponVm {
    return UserCouponVmFromJSONTyped(json, false);
}

export function UserCouponVmFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCouponVm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'expireDate': !exists(json, 'expireDate') ? undefined : (new Date(json['expireDate'])),
        'type': !exists(json, 'type') ? undefined : CouponTypeFromJSON(json['type']),
        'discountValue': !exists(json, 'discountValue') ? undefined : json['discountValue'],
    };
}

export function UserCouponVmToJSON(value?: UserCouponVm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'expireDate': value.expireDate === undefined ? undefined : (value.expireDate.toISOString()),
        'type': CouponTypeToJSON(value.type),
        'discountValue': value.discountValue,
    };
}


