# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  DockerImageName: 'nkm-rtd-246410/couponmanager'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  displayName: 'Install Node.js'

- script: |
    npm install --silent
    npm run build
  displayName: 'npm install and build'

- task: Docker@0
  displayName: 'Build image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'NKM-RTD-GCP-DockerRegistry'
    imageName: '$(DockerImageName):$(Build.BuildId)'
    dockerfile: 'Dockerfile'

- task: Docker@0
  displayName: 'Publish image'
  inputs:
    containerregistrytype: 'Container Registry'
    dockerRegistryConnection: 'NKM-RTD-GCP-DockerRegistry'
    action: 'Push an image'
    imageName: '$(DockerImageName):$(Build.BuildId)'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
