/* tslint:disable */
/* eslint-disable */
/**
 * NKM PKM Coupon Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    UserDto,
    UserDtoFromJSON,
    UserDtoToJSON,
    UserVm,
    UserVmFromJSON,
    UserVmToJSON,
} from '../models';

export interface AuthLoginRequest {
    userDto?: UserDto;
}

export interface AuthRegisterRequest {
    userDto?: UserDto;
}

/**
 * no description
 */
export class AuthApi extends runtime.BaseAPI {

    /**
     */
    async authLoginRaw(requestParameters: AuthLoginRequest): Promise<runtime.ApiResponse<UserVm>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Auth/Login`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserDtoToJSON(requestParameters.userDto),
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => UserVmFromJSON(jsonValue));
    }

    /**
     */
    async authLogin(requestParameters: AuthLoginRequest): Promise<UserVm> {
        const response = await this.authLoginRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async authRegisterRaw(requestParameters: AuthRegisterRequest): Promise<runtime.ApiResponse<void>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/Auth/Register`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: UserDtoToJSON(requestParameters.userDto),
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async authRegister(requestParameters: AuthRegisterRequest): Promise<void> {
        await this.authRegisterRaw(requestParameters);
    }

}
