/* tslint:disable */
/* eslint-disable */
/**
 * Optima Coupon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

export interface NotificationHubEventsRequest {
    xOPTIMATransactionGuid?: string;
}

export interface TestCampaignMovedToWaitingStateNotificationRequest {
    xOPTIMATransactionGuid?: string;
}

/**
 * no description
 */
export class NotificationHubApi extends runtime.BaseAPI {

    /**
     */
    async notificationHubEventsRaw(requestParameters: NotificationHubEventsRequest): Promise<runtime.ApiResponse<Array<string>>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xOPTIMATransactionGuid !== undefined && requestParameters.xOPTIMATransactionGuid !== null) {
            headerParameters['X-OPTIMA-Transaction-Guid'] = String(requestParameters.xOPTIMATransactionGuid);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/NotificationHub/Events`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async notificationHubEvents(requestParameters: NotificationHubEventsRequest): Promise<Array<string>> {
        const response = await this.notificationHubEventsRaw(requestParameters);
        return await response.value();
    }

    /**
     */
    async testCampaignMovedToWaitingStateNotificationRaw(requestParameters: TestCampaignMovedToWaitingStateNotificationRequest): Promise<runtime.ApiResponse<void>> {
        const queryParameters: runtime.HTTPQuery = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (requestParameters.xOPTIMATransactionGuid !== undefined && requestParameters.xOPTIMATransactionGuid !== null) {
            headerParameters['X-OPTIMA-Transaction-Guid'] = String(requestParameters.xOPTIMATransactionGuid);
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = this.configuration.apiKey("Authorization"); // Bearer authentication
        }

        const response = await this.request({
            path: `/api/NotificationHub/TestCampaignMovedToWaitingStateNotification`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async testCampaignMovedToWaitingStateNotification(requestParameters: TestCampaignMovedToWaitingStateNotificationRequest): Promise<void> {
        await this.testCampaignMovedToWaitingStateNotificationRaw(requestParameters);
    }

}
