/* tslint:disable */
/* eslint-disable */
/**
 * Optima Coupon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum CouponMode {
    Physical = 'Physical',
    Online = 'Online'
}

export function CouponModeFromJSON(json: any): CouponMode {
    return CouponModeFromJSONTyped(json, false);
}

export function CouponModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CouponMode {
    return json as CouponMode;
}

export function CouponModeToJSON(value?: CouponMode | null): any {
    return value as any;
}

