/* tslint:disable */
/* eslint-disable */
/**
 * Optima Coupon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EmailTemplateVersionDto
 */
export interface EmailTemplateVersionDto {
    /**
     * 
     * @type {string}
     * @memberof EmailTemplateVersionDto
     */
    content?: string | null;
}

export function EmailTemplateVersionDtoFromJSON(json: any): EmailTemplateVersionDto {
    return EmailTemplateVersionDtoFromJSONTyped(json, false);
}

export function EmailTemplateVersionDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EmailTemplateVersionDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'content': !exists(json, 'content') ? undefined : json['content'],
    };
}

export function EmailTemplateVersionDtoToJSON(value?: EmailTemplateVersionDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'content': value.content,
    };
}


