/* tslint:disable */
/* eslint-disable */
/**
 * Optima Coupon
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ScoringEventType,
    ScoringEventTypeFromJSON,
    ScoringEventTypeFromJSONTyped,
    ScoringEventTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface ScoreEventVm
 */
export interface ScoreEventVm {
    /**
     * 
     * @type {ScoringEventType}
     * @memberof ScoreEventVm
     */
    evenType?: ScoringEventType;
    /**
     * 
     * @type {Date}
     * @memberof ScoreEventVm
     */
    dateTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof ScoreEventVm
     */
    score?: number;
}

export function ScoreEventVmFromJSON(json: any): ScoreEventVm {
    return ScoreEventVmFromJSONTyped(json, false);
}

export function ScoreEventVmFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScoreEventVm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'evenType': !exists(json, 'evenType') ? undefined : ScoringEventTypeFromJSON(json['evenType']),
        'dateTime': !exists(json, 'dateTime') ? undefined : (new Date(json['dateTime'])),
        'score': !exists(json, 'score') ? undefined : json['score'],
    };
}

export function ScoreEventVmToJSON(value?: ScoreEventVm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'evenType': ScoringEventTypeToJSON(value.evenType),
        'dateTime': value.dateTime === undefined ? undefined : (value.dateTime.toISOString()),
        'score': value.score,
    };
}


