/* tslint:disable */
/* eslint-disable */
/**
 * NKM PKM Admin Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CompanyVm,
    CompanyVmFromJSON,
    CompanyVmFromJSONTyped,
    CompanyVmToJSON,
} from './';

/**
 * 
 * @export
 * @interface CompanyVmPaginatedResponse
 */
export interface CompanyVmPaginatedResponse {
    /**
     * 
     * @type {Array<CompanyVm>}
     * @memberof CompanyVmPaginatedResponse
     */
    result?: Array<CompanyVm> | null;
    /**
     * 
     * @type {number}
     * @memberof CompanyVmPaginatedResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyVmPaginatedResponse
     */
    from?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyVmPaginatedResponse
     */
    to?: number;
    /**
     * 
     * @type {number}
     * @memberof CompanyVmPaginatedResponse
     */
    size?: number;
}

export function CompanyVmPaginatedResponseFromJSON(json: any): CompanyVmPaginatedResponse {
    return CompanyVmPaginatedResponseFromJSONTyped(json, false);
}

export function CompanyVmPaginatedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompanyVmPaginatedResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'result': !exists(json, 'result') ? undefined : (json['result'] === null ? null : (json['result'] as Array<any>).map(CompanyVmFromJSON)),
        'page': !exists(json, 'page') ? undefined : json['page'],
        'from': !exists(json, 'from') ? undefined : json['from'],
        'to': !exists(json, 'to') ? undefined : json['to'],
        'size': !exists(json, 'size') ? undefined : json['size'],
    };
}

export function CompanyVmPaginatedResponseToJSON(value?: CompanyVmPaginatedResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'result': value.result === undefined ? undefined : (value.result === null ? null : (value.result as Array<any>).map(CompanyVmToJSON)),
        'page': value.page,
        'from': value.from,
        'to': value.to,
        'size': value.size,
    };
}


