/* tslint:disable */
/* eslint-disable */
/**
 * Optima Admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationGroupVm
 */
export interface OrganizationGroupVm {
    /**
     * 
     * @type {number}
     * @memberof OrganizationGroupVm
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof OrganizationGroupVm
     */
    name?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof OrganizationGroupVm
     */
    createdDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof OrganizationGroupVm
     */
    createdBy?: string | null;
    /**
     * 
     * @type {number}
     * @memberof OrganizationGroupVm
     */
    profileCount?: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizationGroupVm
     */
    companyCount?: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizationGroupVm
     */
    jobRoleCount?: number;
    /**
     * 
     * @type {number}
     * @memberof OrganizationGroupVm
     */
    permissionsCount?: number;
}

export function OrganizationGroupVmFromJSON(json: any): OrganizationGroupVm {
    return OrganizationGroupVmFromJSONTyped(json, false);
}

export function OrganizationGroupVmFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationGroupVm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'createdDate': !exists(json, 'createdDate') ? undefined : (new Date(json['createdDate'])),
        'createdBy': !exists(json, 'createdBy') ? undefined : json['createdBy'],
        'profileCount': !exists(json, 'profileCount') ? undefined : json['profileCount'],
        'companyCount': !exists(json, 'companyCount') ? undefined : json['companyCount'],
        'jobRoleCount': !exists(json, 'jobRoleCount') ? undefined : json['jobRoleCount'],
        'permissionsCount': !exists(json, 'permissionsCount') ? undefined : json['permissionsCount'],
    };
}

export function OrganizationGroupVmToJSON(value?: OrganizationGroupVm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'createdDate': value.createdDate === undefined ? undefined : (value.createdDate.toISOString()),
        'createdBy': value.createdBy,
        'profileCount': value.profileCount,
        'companyCount': value.companyCount,
        'jobRoleCount': value.jobRoleCount,
        'permissionsCount': value.permissionsCount,
    };
}


