/* tslint:disable */
/* eslint-disable */
/**
 * NKM PKM Admin Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ProfileStatus,
    ProfileStatusFromJSON,
    ProfileStatusFromJSONTyped,
    ProfileStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProfileDto
 */
export interface ProfileDto {
    /**
     * 
     * @type {string}
     * @memberof ProfileDto
     */
    name?: string | null;
    /**
     * 
     * @type {ProfileStatus}
     * @memberof ProfileDto
     */
    status?: ProfileStatus;
    /**
     * 
     * @type {string}
     * @memberof ProfileDto
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ProfileDto
     */
    email?: string | null;
}

export function ProfileDtoFromJSON(json: any): ProfileDto {
    return ProfileDtoFromJSONTyped(json, false);
}

export function ProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProfileDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'status': !exists(json, 'status') ? undefined : ProfileStatusFromJSON(json['status']),
        'userName': !exists(json, 'userName') ? undefined : json['userName'],
        'email': !exists(json, 'email') ? undefined : json['email'],
    };
}

export function ProfileDtoToJSON(value?: ProfileDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'status': ProfileStatusToJSON(value.status),
        'userName': value.userName,
        'email': value.email,
    };
}


