/* tslint:disable */
/* eslint-disable */
/**
 * NKM RTD CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CampaignTestGroupCategoryModel,
    CampaignTestGroupCategoryModelFromJSON,
    CampaignTestGroupCategoryModelFromJSONTyped,
    CampaignTestGroupCategoryModelToJSON,
} from './';

/**
 * 
 * @export
 * @interface AssignTestGroupCategoriesModel
 */
export interface AssignTestGroupCategoriesModel {
    /**
     * 
     * @type {number}
     * @memberof AssignTestGroupCategoriesModel
     */
    campaignId: number;
    /**
     * 
     * @type {Array<CampaignTestGroupCategoryModel>}
     * @memberof AssignTestGroupCategoriesModel
     */
    campaignTestGroupCategories: Array<CampaignTestGroupCategoryModel>;
    /**
     * 
     * @type {boolean}
     * @memberof AssignTestGroupCategoriesModel
     */
    isTestGroupMailsAlreadySentOut?: boolean;
}

export function AssignTestGroupCategoriesModelFromJSON(json: any): AssignTestGroupCategoriesModel {
    return AssignTestGroupCategoriesModelFromJSONTyped(json, false);
}

export function AssignTestGroupCategoriesModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignTestGroupCategoriesModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'campaignId': json['campaignId'],
        'campaignTestGroupCategories': ((json['campaignTestGroupCategories'] as Array<any>).map(CampaignTestGroupCategoryModelFromJSON)),
        'isTestGroupMailsAlreadySentOut': !exists(json, 'isTestGroupMailsAlreadySentOut') ? undefined : json['isTestGroupMailsAlreadySentOut'],
    };
}

export function AssignTestGroupCategoriesModelToJSON(value?: AssignTestGroupCategoriesModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'campaignId': value.campaignId,
        'campaignTestGroupCategories': ((value.campaignTestGroupCategories as Array<any>).map(CampaignTestGroupCategoryModelToJSON)),
        'isTestGroupMailsAlreadySentOut': value.isTestGroupMailsAlreadySentOut,
    };
}


