/* tslint:disable */
/* eslint-disable */
/**
 * NKM RTD CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    PermissionModel,
    PermissionModelFromJSON,
    PermissionModelFromJSONTyped,
    PermissionModelToJSON,
} from './';

/**
 * 
 * @export
 * @interface PermissionModelPaginatedSearchResponse
 */
export interface PermissionModelPaginatedSearchResponse {
    /**
     * 
     * @type {Array<PermissionModel>}
     * @memberof PermissionModelPaginatedSearchResponse
     */
    items?: Array<PermissionModel> | null;
    /**
     * 
     * @type {number}
     * @memberof PermissionModelPaginatedSearchResponse
     */
    totalCount?: number;
}

export function PermissionModelPaginatedSearchResponseFromJSON(json: any): PermissionModelPaginatedSearchResponse {
    return PermissionModelPaginatedSearchResponseFromJSONTyped(json, false);
}

export function PermissionModelPaginatedSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PermissionModelPaginatedSearchResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(PermissionModelFromJSON)),
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
    };
}

export function PermissionModelPaginatedSearchResponseToJSON(value?: PermissionModelPaginatedSearchResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(PermissionModelToJSON)),
        'totalCount': value.totalCount,
    };
}


