/* tslint:disable */
/* eslint-disable */
/**
 * NKM RTD CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleTestGroupCategoryModel
 */
export interface SimpleTestGroupCategoryModel {
    /**
     * 
     * @type {number}
     * @memberof SimpleTestGroupCategoryModel
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SimpleTestGroupCategoryModel
     */
    name?: string | null;
}

export function SimpleTestGroupCategoryModelFromJSON(json: any): SimpleTestGroupCategoryModel {
    return SimpleTestGroupCategoryModelFromJSONTyped(json, false);
}

export function SimpleTestGroupCategoryModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleTestGroupCategoryModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
    };
}

export function SimpleTestGroupCategoryModelToJSON(value?: SimpleTestGroupCategoryModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}


