/* tslint:disable */
/* eslint-disable */
/**
 * NKM RTD CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SimpleTestGroupCategoryModel,
    SimpleTestGroupCategoryModelFromJSON,
    SimpleTestGroupCategoryModelFromJSONTyped,
    SimpleTestGroupCategoryModelToJSON,
    UserDto,
    UserDtoFromJSON,
    UserDtoFromJSONTyped,
    UserDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface CampaignTestGroupCategoryModel
 */
export interface CampaignTestGroupCategoryModel {
    /**
     * 
     * @type {SimpleTestGroupCategoryModel}
     * @memberof CampaignTestGroupCategoryModel
     */
    testGroupCategory?: SimpleTestGroupCategoryModel | null;
    /**
     * 
     * @type {Array<UserDto>}
     * @memberof CampaignTestGroupCategoryModel
     */
    users?: Array<UserDto> | null;
}

export function CampaignTestGroupCategoryModelFromJSON(json: any): CampaignTestGroupCategoryModel {
    return CampaignTestGroupCategoryModelFromJSONTyped(json, false);
}

export function CampaignTestGroupCategoryModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CampaignTestGroupCategoryModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'testGroupCategory': !exists(json, 'testGroupCategory') ? undefined : SimpleTestGroupCategoryModelFromJSON(json['testGroupCategory']),
        'users': !exists(json, 'users') ? undefined : (json['users'] === null ? null : (json['users'] as Array<any>).map(UserDtoFromJSON)),
    };
}

export function CampaignTestGroupCategoryModelToJSON(value?: CampaignTestGroupCategoryModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'testGroupCategory': SimpleTestGroupCategoryModelToJSON(value.testGroupCategory),
        'users': value.users === undefined ? undefined : (value.users === null ? null : (value.users as Array<any>).map(UserDtoToJSON)),
    };
}


