/* tslint:disable */
/* eslint-disable */
/**
 * NKM RTD CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32,
    NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32FromJSON,
    NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32FromJSONTyped,
    NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32ToJSON,
} from './';

/**
 * 
 * @export
 * @interface NKMRTDCampaignEditorPrototypesCreateCampaignVm
 */
export interface NKMRTDCampaignEditorPrototypesCreateCampaignVm {
    /**
     * 
     * @type {Array<NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32>}
     * @memberof NKMRTDCampaignEditorPrototypesCreateCampaignVm
     */
    departments?: Array<NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32> | null;
    /**
     * 
     * @type {Array<NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32>}
     * @memberof NKMRTDCampaignEditorPrototypesCreateCampaignVm
     */
    products?: Array<NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32> | null;
    /**
     * 
     * @type {Array<NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32>}
     * @memberof NKMRTDCampaignEditorPrototypesCreateCampaignVm
     */
    responsibles?: Array<NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32> | null;
    /**
     * 
     * @type {Array<NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32>}
     * @memberof NKMRTDCampaignEditorPrototypesCreateCampaignVm
     */
    requesters?: Array<NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32> | null;
    /**
     * 
     * @type {Array<NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32>}
     * @memberof NKMRTDCampaignEditorPrototypesCreateCampaignVm
     */
    serviceTypes?: Array<NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32> | null;
    /**
     * 
     * @type {Array<NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32>}
     * @memberof NKMRTDCampaignEditorPrototypesCreateCampaignVm
     */
    businessTypes?: Array<NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32> | null;
    /**
     * 
     * @type {Array<NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32>}
     * @memberof NKMRTDCampaignEditorPrototypesCreateCampaignVm
     */
    marketTypes?: Array<NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32> | null;
    /**
     * 
     * @type {Array<NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32>}
     * @memberof NKMRTDCampaignEditorPrototypesCreateCampaignVm
     */
    productTypes?: Array<NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32> | null;
}

export function NKMRTDCampaignEditorPrototypesCreateCampaignVmFromJSON(json: any): NKMRTDCampaignEditorPrototypesCreateCampaignVm {
    return NKMRTDCampaignEditorPrototypesCreateCampaignVmFromJSONTyped(json, false);
}

export function NKMRTDCampaignEditorPrototypesCreateCampaignVmFromJSONTyped(json: any, ignoreDiscriminator: boolean): NKMRTDCampaignEditorPrototypesCreateCampaignVm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'departments': !exists(json, 'departments') ? undefined : (json['departments'] === null ? null : (json['departments'] as Array<any>).map(NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32FromJSON)),
        'products': !exists(json, 'products') ? undefined : (json['products'] === null ? null : (json['products'] as Array<any>).map(NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32FromJSON)),
        'responsibles': !exists(json, 'responsibles') ? undefined : (json['responsibles'] === null ? null : (json['responsibles'] as Array<any>).map(NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32FromJSON)),
        'requesters': !exists(json, 'requesters') ? undefined : (json['requesters'] === null ? null : (json['requesters'] as Array<any>).map(NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32FromJSON)),
        'serviceTypes': !exists(json, 'serviceTypes') ? undefined : (json['serviceTypes'] === null ? null : (json['serviceTypes'] as Array<any>).map(NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32FromJSON)),
        'businessTypes': !exists(json, 'businessTypes') ? undefined : (json['businessTypes'] === null ? null : (json['businessTypes'] as Array<any>).map(NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32FromJSON)),
        'marketTypes': !exists(json, 'marketTypes') ? undefined : (json['marketTypes'] === null ? null : (json['marketTypes'] as Array<any>).map(NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32FromJSON)),
        'productTypes': !exists(json, 'productTypes') ? undefined : (json['productTypes'] === null ? null : (json['productTypes'] as Array<any>).map(NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32FromJSON)),
    };
}

export function NKMRTDCampaignEditorPrototypesCreateCampaignVmToJSON(value?: NKMRTDCampaignEditorPrototypesCreateCampaignVm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'departments': value.departments === undefined ? undefined : (value.departments === null ? null : (value.departments as Array<any>).map(NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32ToJSON)),
        'products': value.products === undefined ? undefined : (value.products === null ? null : (value.products as Array<any>).map(NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32ToJSON)),
        'responsibles': value.responsibles === undefined ? undefined : (value.responsibles === null ? null : (value.responsibles as Array<any>).map(NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32ToJSON)),
        'requesters': value.requesters === undefined ? undefined : (value.requesters === null ? null : (value.requesters as Array<any>).map(NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32ToJSON)),
        'serviceTypes': value.serviceTypes === undefined ? undefined : (value.serviceTypes === null ? null : (value.serviceTypes as Array<any>).map(NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32ToJSON)),
        'businessTypes': value.businessTypes === undefined ? undefined : (value.businessTypes === null ? null : (value.businessTypes as Array<any>).map(NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32ToJSON)),
        'marketTypes': value.marketTypes === undefined ? undefined : (value.marketTypes === null ? null : (value.marketTypes as Array<any>).map(NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32ToJSON)),
        'productTypes': value.productTypes === undefined ? undefined : (value.productTypes === null ? null : (value.productTypes as Array<any>).map(NKMRTDApplicationModelsViewModelsLabelValuePairOfSystemInt32ToJSON)),
    };
}


