/* tslint:disable */
/* eslint-disable */
/**
 * NKM RTD CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NKMRTDCampaignEditorApplicationCommonMessagesRequestsUserExtensionInfoBase,
    NKMRTDCampaignEditorApplicationCommonMessagesRequestsUserExtensionInfoBaseFromJSON,
    NKMRTDCampaignEditorApplicationCommonMessagesRequestsUserExtensionInfoBaseFromJSONTyped,
    NKMRTDCampaignEditorApplicationCommonMessagesRequestsUserExtensionInfoBaseToJSON,
} from './';

/**
 * 
 * @export
 * @interface NKMRTDCampaignEditorApplicationStandaloneUsersCommandsChangeForgotPasswordChangeForgotPasswordCommand
 */
export interface NKMRTDCampaignEditorApplicationStandaloneUsersCommandsChangeForgotPasswordChangeForgotPasswordCommand {
    /**
     * 
     * @type {string}
     * @memberof NKMRTDCampaignEditorApplicationStandaloneUsersCommandsChangeForgotPasswordChangeForgotPasswordCommand
     */
    guid?: string;
    /**
     * 
     * @type {string}
     * @memberof NKMRTDCampaignEditorApplicationStandaloneUsersCommandsChangeForgotPasswordChangeForgotPasswordCommand
     */
    newPassword?: string | null;
    /**
     * 
     * @type {NKMRTDCampaignEditorApplicationCommonMessagesRequestsUserExtensionInfoBase}
     * @memberof NKMRTDCampaignEditorApplicationStandaloneUsersCommandsChangeForgotPasswordChangeForgotPasswordCommand
     */
    extensionInfo?: NKMRTDCampaignEditorApplicationCommonMessagesRequestsUserExtensionInfoBase | null;
}

export function NKMRTDCampaignEditorApplicationStandaloneUsersCommandsChangeForgotPasswordChangeForgotPasswordCommandFromJSON(json: any): NKMRTDCampaignEditorApplicationStandaloneUsersCommandsChangeForgotPasswordChangeForgotPasswordCommand {
    return NKMRTDCampaignEditorApplicationStandaloneUsersCommandsChangeForgotPasswordChangeForgotPasswordCommandFromJSONTyped(json, false);
}

export function NKMRTDCampaignEditorApplicationStandaloneUsersCommandsChangeForgotPasswordChangeForgotPasswordCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): NKMRTDCampaignEditorApplicationStandaloneUsersCommandsChangeForgotPasswordChangeForgotPasswordCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'guid': !exists(json, 'guid') ? undefined : json['guid'],
        'newPassword': !exists(json, 'newPassword') ? undefined : json['newPassword'],
        'extensionInfo': !exists(json, 'extensionInfo') ? undefined : NKMRTDCampaignEditorApplicationCommonMessagesRequestsUserExtensionInfoBaseFromJSON(json['extensionInfo']),
    };
}

export function NKMRTDCampaignEditorApplicationStandaloneUsersCommandsChangeForgotPasswordChangeForgotPasswordCommandToJSON(value?: NKMRTDCampaignEditorApplicationStandaloneUsersCommandsChangeForgotPasswordChangeForgotPasswordCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'guid': value.guid,
        'newPassword': value.newPassword,
        'extensionInfo': NKMRTDCampaignEditorApplicationCommonMessagesRequestsUserExtensionInfoBaseToJSON(value.extensionInfo),
    };
}


