/* tslint:disable */
/* eslint-disable */
/**
 * NKM RTD CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NKMRTDCampaignEditorPrototypesCampaignResultEventVm
 */
export interface NKMRTDCampaignEditorPrototypesCampaignResultEventVm {
    /**
     * 
     * @type {number}
     * @memberof NKMRTDCampaignEditorPrototypesCampaignResultEventVm
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof NKMRTDCampaignEditorPrototypesCampaignResultEventVm
     */
    campaignName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NKMRTDCampaignEditorPrototypesCampaignResultEventVm
     */
    campaignTechnicalName?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof NKMRTDCampaignEditorPrototypesCampaignResultEventVm
     */
    createdDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof NKMRTDCampaignEditorPrototypesCampaignResultEventVm
     */
    bpId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NKMRTDCampaignEditorPrototypesCampaignResultEventVm
     */
    contact?: string | null;
    /**
     * 
     * @type {number}
     * @memberof NKMRTDCampaignEditorPrototypesCampaignResultEventVm
     */
    channelId?: number;
    /**
     * 
     * @type {string}
     * @memberof NKMRTDCampaignEditorPrototypesCampaignResultEventVm
     */
    event?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NKMRTDCampaignEditorPrototypesCampaignResultEventVm
     */
    eventResult?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NKMRTDCampaignEditorPrototypesCampaignResultEventVm
     */
    campaignResult?: string | null;
    /**
     * 
     * @type {number}
     * @memberof NKMRTDCampaignEditorPrototypesCampaignResultEventVm
     */
    templateId?: number | null;
}

export function NKMRTDCampaignEditorPrototypesCampaignResultEventVmFromJSON(json: any): NKMRTDCampaignEditorPrototypesCampaignResultEventVm {
    return NKMRTDCampaignEditorPrototypesCampaignResultEventVmFromJSONTyped(json, false);
}

export function NKMRTDCampaignEditorPrototypesCampaignResultEventVmFromJSONTyped(json: any, ignoreDiscriminator: boolean): NKMRTDCampaignEditorPrototypesCampaignResultEventVm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'campaignName': !exists(json, 'campaignName') ? undefined : json['campaignName'],
        'campaignTechnicalName': !exists(json, 'campaignTechnicalName') ? undefined : json['campaignTechnicalName'],
        'createdDate': !exists(json, 'createdDate') ? undefined : (new Date(json['createdDate'])),
        'bpId': !exists(json, 'bpId') ? undefined : json['bpId'],
        'contact': !exists(json, 'contact') ? undefined : json['contact'],
        'channelId': !exists(json, 'channelId') ? undefined : json['channelId'],
        'event': !exists(json, 'event') ? undefined : json['event'],
        'eventResult': !exists(json, 'eventResult') ? undefined : json['eventResult'],
        'campaignResult': !exists(json, 'campaignResult') ? undefined : json['campaignResult'],
        'templateId': !exists(json, 'templateId') ? undefined : json['templateId'],
    };
}

export function NKMRTDCampaignEditorPrototypesCampaignResultEventVmToJSON(value?: NKMRTDCampaignEditorPrototypesCampaignResultEventVm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'campaignName': value.campaignName,
        'campaignTechnicalName': value.campaignTechnicalName,
        'createdDate': value.createdDate === undefined ? undefined : (value.createdDate.toISOString()),
        'bpId': value.bpId,
        'contact': value.contact,
        'channelId': value.channelId,
        'event': value.event,
        'eventResult': value.eventResult,
        'campaignResult': value.campaignResult,
        'templateId': value.templateId,
    };
}


