/* tslint:disable */
/* eslint-disable */
/**
 * NKM RTD CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NKMRTDCampaignEditorPrototypesAdGroupVm,
    NKMRTDCampaignEditorPrototypesAdGroupVmFromJSON,
    NKMRTDCampaignEditorPrototypesAdGroupVmFromJSONTyped,
    NKMRTDCampaignEditorPrototypesAdGroupVmToJSON,
    NKMRTDCampaignEditorPrototypesFunctionPermissionVm,
    NKMRTDCampaignEditorPrototypesFunctionPermissionVmFromJSON,
    NKMRTDCampaignEditorPrototypesFunctionPermissionVmFromJSONTyped,
    NKMRTDCampaignEditorPrototypesFunctionPermissionVmToJSON,
    NKMRTDCampaignEditorPrototypesUserPermissionVm,
    NKMRTDCampaignEditorPrototypesUserPermissionVmFromJSON,
    NKMRTDCampaignEditorPrototypesUserPermissionVmFromJSONTyped,
    NKMRTDCampaignEditorPrototypesUserPermissionVmToJSON,
} from './';

/**
 * 
 * @export
 * @interface NKMRTDCampaignEditorPermissionsCommandsCreatePermissionCreatePermissionCommand
 */
export interface NKMRTDCampaignEditorPermissionsCommandsCreatePermissionCreatePermissionCommand {
    /**
     * Name of the permission.
     * @type {string}
     * @memberof NKMRTDCampaignEditorPermissionsCommandsCreatePermissionCreatePermissionCommand
     */
    name?: string | null;
    /**
     * A list of ad groups that belong to this permission.  Use IsSelected to define if the connection is active.
     * @type {Array<NKMRTDCampaignEditorPrototypesAdGroupVm>}
     * @memberof NKMRTDCampaignEditorPermissionsCommandsCreatePermissionCreatePermissionCommand
     */
    adGroups?: Array<NKMRTDCampaignEditorPrototypesAdGroupVm> | null;
    /**
     * A list of users that belong to this permission.  Use IsSelected to define if the connection is active.
     * @type {Array<NKMRTDCampaignEditorPrototypesUserPermissionVm>}
     * @memberof NKMRTDCampaignEditorPermissionsCommandsCreatePermissionCreatePermissionCommand
     */
    users?: Array<NKMRTDCampaignEditorPrototypesUserPermissionVm> | null;
    /**
     * A list of function permissions that belong to this permission.
     * @type {Array<NKMRTDCampaignEditorPrototypesFunctionPermissionVm>}
     * @memberof NKMRTDCampaignEditorPermissionsCommandsCreatePermissionCreatePermissionCommand
     */
    functionPermissions?: Array<NKMRTDCampaignEditorPrototypesFunctionPermissionVm> | null;
}

export function NKMRTDCampaignEditorPermissionsCommandsCreatePermissionCreatePermissionCommandFromJSON(json: any): NKMRTDCampaignEditorPermissionsCommandsCreatePermissionCreatePermissionCommand {
    return NKMRTDCampaignEditorPermissionsCommandsCreatePermissionCreatePermissionCommandFromJSONTyped(json, false);
}

export function NKMRTDCampaignEditorPermissionsCommandsCreatePermissionCreatePermissionCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): NKMRTDCampaignEditorPermissionsCommandsCreatePermissionCreatePermissionCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'adGroups': !exists(json, 'adGroups') ? undefined : (json['adGroups'] === null ? null : (json['adGroups'] as Array<any>).map(NKMRTDCampaignEditorPrototypesAdGroupVmFromJSON)),
        'users': !exists(json, 'users') ? undefined : (json['users'] === null ? null : (json['users'] as Array<any>).map(NKMRTDCampaignEditorPrototypesUserPermissionVmFromJSON)),
        'functionPermissions': !exists(json, 'functionPermissions') ? undefined : (json['functionPermissions'] === null ? null : (json['functionPermissions'] as Array<any>).map(NKMRTDCampaignEditorPrototypesFunctionPermissionVmFromJSON)),
    };
}

export function NKMRTDCampaignEditorPermissionsCommandsCreatePermissionCreatePermissionCommandToJSON(value?: NKMRTDCampaignEditorPermissionsCommandsCreatePermissionCreatePermissionCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'adGroups': value.adGroups === undefined ? undefined : (value.adGroups === null ? null : (value.adGroups as Array<any>).map(NKMRTDCampaignEditorPrototypesAdGroupVmToJSON)),
        'users': value.users === undefined ? undefined : (value.users === null ? null : (value.users as Array<any>).map(NKMRTDCampaignEditorPrototypesUserPermissionVmToJSON)),
        'functionPermissions': value.functionPermissions === undefined ? undefined : (value.functionPermissions === null ? null : (value.functionPermissions as Array<any>).map(NKMRTDCampaignEditorPrototypesFunctionPermissionVmToJSON)),
    };
}


