/* tslint:disable */
/* eslint-disable */
/**
 * NKM RTD CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NKMRTDApplicationEnumsQueryConditionOperation,
    NKMRTDApplicationEnumsQueryConditionOperationFromJSON,
    NKMRTDApplicationEnumsQueryConditionOperationFromJSONTyped,
    NKMRTDApplicationEnumsQueryConditionOperationToJSON,
} from './';

/**
 * 
 * @export
 * @interface NKMRTDApplicationModelsViewModelsSegmentConditionVm
 */
export interface NKMRTDApplicationModelsViewModelsSegmentConditionVm {
    /**
     * 
     * @type {string}
     * @memberof NKMRTDApplicationModelsViewModelsSegmentConditionVm
     */
    ruleId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NKMRTDApplicationModelsViewModelsSegmentConditionVm
     */
    label?: string | null;
    /**
     * 
     * @type {NKMRTDApplicationEnumsQueryConditionOperation}
     * @memberof NKMRTDApplicationModelsViewModelsSegmentConditionVm
     */
    operation?: NKMRTDApplicationEnumsQueryConditionOperation;
    /**
     * 
     * @type {string}
     * @memberof NKMRTDApplicationModelsViewModelsSegmentConditionVm
     */
    operator?: string | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof NKMRTDApplicationModelsViewModelsSegmentConditionVm
     */
    values?: Array<string> | null;
}

export function NKMRTDApplicationModelsViewModelsSegmentConditionVmFromJSON(json: any): NKMRTDApplicationModelsViewModelsSegmentConditionVm {
    return NKMRTDApplicationModelsViewModelsSegmentConditionVmFromJSONTyped(json, false);
}

export function NKMRTDApplicationModelsViewModelsSegmentConditionVmFromJSONTyped(json: any, ignoreDiscriminator: boolean): NKMRTDApplicationModelsViewModelsSegmentConditionVm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'ruleId': !exists(json, 'ruleId') ? undefined : json['ruleId'],
        'label': !exists(json, 'label') ? undefined : json['label'],
        'operation': !exists(json, 'operation') ? undefined : NKMRTDApplicationEnumsQueryConditionOperationFromJSON(json['operation']),
        'operator': !exists(json, 'operator') ? undefined : json['operator'],
        'values': !exists(json, 'values') ? undefined : json['values'],
    };
}

export function NKMRTDApplicationModelsViewModelsSegmentConditionVmToJSON(value?: NKMRTDApplicationModelsViewModelsSegmentConditionVm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'ruleId': value.ruleId,
        'label': value.label,
        'operation': NKMRTDApplicationEnumsQueryConditionOperationToJSON(value.operation),
        'operator': value.operator,
        'values': value.values,
    };
}


