/* tslint:disable */
/* eslint-disable */
/**
 * NKM RTD CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NKMRTDCampaignEditorApplicationCommonMessagesViewModelsTestGroupCategoryWithNameVm,
    NKMRTDCampaignEditorApplicationCommonMessagesViewModelsTestGroupCategoryWithNameVmFromJSON,
    NKMRTDCampaignEditorApplicationCommonMessagesViewModelsTestGroupCategoryWithNameVmFromJSONTyped,
    NKMRTDCampaignEditorApplicationCommonMessagesViewModelsTestGroupCategoryWithNameVmToJSON,
    NKMRTDCampaignEditorApplicationCommonMessagesViewModelsUserVm,
    NKMRTDCampaignEditorApplicationCommonMessagesViewModelsUserVmFromJSON,
    NKMRTDCampaignEditorApplicationCommonMessagesViewModelsUserVmFromJSONTyped,
    NKMRTDCampaignEditorApplicationCommonMessagesViewModelsUserVmToJSON,
} from './';

/**
 * 
 * @export
 * @interface NKMRTDCampaignEditorApplicationCommonMessagesViewModelsCampaignTestGroupCategoryVm
 */
export interface NKMRTDCampaignEditorApplicationCommonMessagesViewModelsCampaignTestGroupCategoryVm {
    /**
     * 
     * @type {NKMRTDCampaignEditorApplicationCommonMessagesViewModelsTestGroupCategoryWithNameVm}
     * @memberof NKMRTDCampaignEditorApplicationCommonMessagesViewModelsCampaignTestGroupCategoryVm
     */
    testGroupCategory?: NKMRTDCampaignEditorApplicationCommonMessagesViewModelsTestGroupCategoryWithNameVm | null;
    /**
     * 
     * @type {Array<NKMRTDCampaignEditorApplicationCommonMessagesViewModelsUserVm>}
     * @memberof NKMRTDCampaignEditorApplicationCommonMessagesViewModelsCampaignTestGroupCategoryVm
     */
    users?: Array<NKMRTDCampaignEditorApplicationCommonMessagesViewModelsUserVm> | null;
}

export function NKMRTDCampaignEditorApplicationCommonMessagesViewModelsCampaignTestGroupCategoryVmFromJSON(json: any): NKMRTDCampaignEditorApplicationCommonMessagesViewModelsCampaignTestGroupCategoryVm {
    return NKMRTDCampaignEditorApplicationCommonMessagesViewModelsCampaignTestGroupCategoryVmFromJSONTyped(json, false);
}

export function NKMRTDCampaignEditorApplicationCommonMessagesViewModelsCampaignTestGroupCategoryVmFromJSONTyped(json: any, ignoreDiscriminator: boolean): NKMRTDCampaignEditorApplicationCommonMessagesViewModelsCampaignTestGroupCategoryVm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'testGroupCategory': !exists(json, 'testGroupCategory') ? undefined : NKMRTDCampaignEditorApplicationCommonMessagesViewModelsTestGroupCategoryWithNameVmFromJSON(json['testGroupCategory']),
        'users': !exists(json, 'users') ? undefined : (json['users'] === null ? null : (json['users'] as Array<any>).map(NKMRTDCampaignEditorApplicationCommonMessagesViewModelsUserVmFromJSON)),
    };
}

export function NKMRTDCampaignEditorApplicationCommonMessagesViewModelsCampaignTestGroupCategoryVmToJSON(value?: NKMRTDCampaignEditorApplicationCommonMessagesViewModelsCampaignTestGroupCategoryVm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'testGroupCategory': NKMRTDCampaignEditorApplicationCommonMessagesViewModelsTestGroupCategoryWithNameVmToJSON(value.testGroupCategory),
        'users': value.users === undefined ? undefined : (value.users === null ? null : (value.users as Array<any>).map(NKMRTDCampaignEditorApplicationCommonMessagesViewModelsUserVmToJSON)),
    };
}


