/* tslint:disable */
/* eslint-disable */
/**
 * NKM RTD CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NKMRTDApplicationModelsRequestsEmailTemplateDto
 */
export interface NKMRTDApplicationModelsRequestsEmailTemplateDto {
    /**
     * 
     * @type {number}
     * @memberof NKMRTDApplicationModelsRequestsEmailTemplateDto
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof NKMRTDApplicationModelsRequestsEmailTemplateDto
     */
    discountId?: number;
    /**
     * 
     * @type {string}
     * @memberof NKMRTDApplicationModelsRequestsEmailTemplateDto
     */
    subject?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NKMRTDApplicationModelsRequestsEmailTemplateDto
     */
    body?: string | null;
    /**
     * 
     * @type {number}
     * @memberof NKMRTDApplicationModelsRequestsEmailTemplateDto
     */
    templateTypeId?: number;
}

export function NKMRTDApplicationModelsRequestsEmailTemplateDtoFromJSON(json: any): NKMRTDApplicationModelsRequestsEmailTemplateDto {
    return NKMRTDApplicationModelsRequestsEmailTemplateDtoFromJSONTyped(json, false);
}

export function NKMRTDApplicationModelsRequestsEmailTemplateDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): NKMRTDApplicationModelsRequestsEmailTemplateDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'discountId': !exists(json, 'discountId') ? undefined : json['discountId'],
        'subject': !exists(json, 'subject') ? undefined : json['subject'],
        'body': !exists(json, 'body') ? undefined : json['body'],
        'templateTypeId': !exists(json, 'templateTypeId') ? undefined : json['templateTypeId'],
    };
}

export function NKMRTDApplicationModelsRequestsEmailTemplateDtoToJSON(value?: NKMRTDApplicationModelsRequestsEmailTemplateDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'discountId': value.discountId,
        'subject': value.subject,
        'body': value.body,
        'templateTypeId': value.templateTypeId,
    };
}


