/* tslint:disable */
/* eslint-disable */
/**
 * NKM RTD CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NKMRTDApplicationEnumsSegmentationType,
    NKMRTDApplicationEnumsSegmentationTypeFromJSON,
    NKMRTDApplicationEnumsSegmentationTypeFromJSONTyped,
    NKMRTDApplicationEnumsSegmentationTypeToJSON,
    NKMRTDApplicationModelsViewModelsSegmentationQueryVm,
    NKMRTDApplicationModelsViewModelsSegmentationQueryVmFromJSON,
    NKMRTDApplicationModelsViewModelsSegmentationQueryVmFromJSONTyped,
    NKMRTDApplicationModelsViewModelsSegmentationQueryVmToJSON,
} from './';

/**
 * 
 * @export
 * @interface NKMRTDApplicationModelsViewModelsDiscountSegmentVm
 */
export interface NKMRTDApplicationModelsViewModelsDiscountSegmentVm {
    /**
     * 
     * @type {number}
     * @memberof NKMRTDApplicationModelsViewModelsDiscountSegmentVm
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof NKMRTDApplicationModelsViewModelsDiscountSegmentVm
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NKMRTDApplicationModelsViewModelsDiscountSegmentVm
     */
    segmentDisplayName?: string | null;
    /**
     * 
     * @type {NKMRTDApplicationEnumsSegmentationType}
     * @memberof NKMRTDApplicationModelsViewModelsDiscountSegmentVm
     */
    type?: NKMRTDApplicationEnumsSegmentationType;
    /**
     * 
     * @type {number}
     * @memberof NKMRTDApplicationModelsViewModelsDiscountSegmentVm
     */
    segmentationCategoryId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof NKMRTDApplicationModelsViewModelsDiscountSegmentVm
     */
    segmentationCategoryName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof NKMRTDApplicationModelsViewModelsDiscountSegmentVm
     */
    referenceSegmentationId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NKMRTDApplicationModelsViewModelsDiscountSegmentVm
     */
    segmentSize?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NKMRTDApplicationModelsViewModelsDiscountSegmentVm
     */
    cumulativeIntersection?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NKMRTDApplicationModelsViewModelsDiscountSegmentVm
     */
    businessPartnerCount?: number;
    /**
     * 
     * @type {NKMRTDApplicationModelsViewModelsSegmentationQueryVm}
     * @memberof NKMRTDApplicationModelsViewModelsDiscountSegmentVm
     */
    query?: NKMRTDApplicationModelsViewModelsSegmentationQueryVm | null;
}

export function NKMRTDApplicationModelsViewModelsDiscountSegmentVmFromJSON(json: any): NKMRTDApplicationModelsViewModelsDiscountSegmentVm {
    return NKMRTDApplicationModelsViewModelsDiscountSegmentVmFromJSONTyped(json, false);
}

export function NKMRTDApplicationModelsViewModelsDiscountSegmentVmFromJSONTyped(json: any, ignoreDiscriminator: boolean): NKMRTDApplicationModelsViewModelsDiscountSegmentVm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'segmentDisplayName': !exists(json, 'segmentDisplayName') ? undefined : json['segmentDisplayName'],
        'type': !exists(json, 'type') ? undefined : NKMRTDApplicationEnumsSegmentationTypeFromJSON(json['type']),
        'segmentationCategoryId': !exists(json, 'segmentationCategoryId') ? undefined : json['segmentationCategoryId'],
        'segmentationCategoryName': !exists(json, 'segmentationCategoryName') ? undefined : json['segmentationCategoryName'],
        'referenceSegmentationId': !exists(json, 'referenceSegmentationId') ? undefined : json['referenceSegmentationId'],
        'segmentSize': !exists(json, 'segmentSize') ? undefined : json['segmentSize'],
        'cumulativeIntersection': !exists(json, 'cumulativeIntersection') ? undefined : json['cumulativeIntersection'],
        'businessPartnerCount': !exists(json, 'businessPartnerCount') ? undefined : json['businessPartnerCount'],
        'query': !exists(json, 'query') ? undefined : NKMRTDApplicationModelsViewModelsSegmentationQueryVmFromJSON(json['query']),
    };
}

export function NKMRTDApplicationModelsViewModelsDiscountSegmentVmToJSON(value?: NKMRTDApplicationModelsViewModelsDiscountSegmentVm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'segmentDisplayName': value.segmentDisplayName,
        'type': NKMRTDApplicationEnumsSegmentationTypeToJSON(value.type),
        'segmentationCategoryId': value.segmentationCategoryId,
        'segmentationCategoryName': value.segmentationCategoryName,
        'referenceSegmentationId': value.referenceSegmentationId,
        'segmentSize': value.segmentSize,
        'cumulativeIntersection': value.cumulativeIntersection,
        'businessPartnerCount': value.businessPartnerCount,
        'query': NKMRTDApplicationModelsViewModelsSegmentationQueryVmToJSON(value.query),
    };
}


