/* tslint:disable */
/* eslint-disable */
/**
 * NKM RTD CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NKMRTDApplicationEnumsCondition,
    NKMRTDApplicationEnumsConditionFromJSON,
    NKMRTDApplicationEnumsConditionFromJSONTyped,
    NKMRTDApplicationEnumsConditionToJSON,
    NKMRTDApplicationEnumsControlType,
    NKMRTDApplicationEnumsControlTypeFromJSON,
    NKMRTDApplicationEnumsControlTypeFromJSONTyped,
    NKMRTDApplicationEnumsControlTypeToJSON,
    NKMRTDApplicationEnumsOperator,
    NKMRTDApplicationEnumsOperatorFromJSON,
    NKMRTDApplicationEnumsOperatorFromJSONTyped,
    NKMRTDApplicationEnumsOperatorToJSON,
    NKMRTDApplicationModelsViewModelsQueryValues,
    NKMRTDApplicationModelsViewModelsQueryValuesFromJSON,
    NKMRTDApplicationModelsViewModelsQueryValuesFromJSONTyped,
    NKMRTDApplicationModelsViewModelsQueryValuesToJSON,
} from './';

/**
 * 
 * @export
 * @interface NKMRTDApplicationModelsViewModelsQueryBuilderQuery
 */
export interface NKMRTDApplicationModelsViewModelsQueryBuilderQuery {
    /**
     * 
     * @type {NKMRTDApplicationEnumsCondition}
     * @memberof NKMRTDApplicationModelsViewModelsQueryBuilderQuery
     */
    condition?: NKMRTDApplicationEnumsCondition | null;
    /**
     * 
     * @type {boolean}
     * @memberof NKMRTDApplicationModelsViewModelsQueryBuilderQuery
     */
    not?: boolean;
    /**
     * 
     * @type {string}
     * @memberof NKMRTDApplicationModelsViewModelsQueryBuilderQuery
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof NKMRTDApplicationModelsViewModelsQueryBuilderQuery
     */
    fieldName?: string | null;
    /**
     * 
     * @type {NKMRTDApplicationEnumsOperator}
     * @memberof NKMRTDApplicationModelsViewModelsQueryBuilderQuery
     */
    operator?: NKMRTDApplicationEnumsOperator | null;
    /**
     * 
     * @type {NKMRTDApplicationEnumsControlType}
     * @memberof NKMRTDApplicationModelsViewModelsQueryBuilderQuery
     */
    type?: NKMRTDApplicationEnumsControlType | null;
    /**
     * 
     * @type {Array<NKMRTDApplicationModelsViewModelsQueryBuilderQuery>}
     * @memberof NKMRTDApplicationModelsViewModelsQueryBuilderQuery
     */
    rules?: Array<NKMRTDApplicationModelsViewModelsQueryBuilderQuery> | null;
    /**
     * 
     * @type {Array<NKMRTDApplicationModelsViewModelsQueryValues>}
     * @memberof NKMRTDApplicationModelsViewModelsQueryBuilderQuery
     */
    values?: Array<NKMRTDApplicationModelsViewModelsQueryValues> | null;
}

export function NKMRTDApplicationModelsViewModelsQueryBuilderQueryFromJSON(json: any): NKMRTDApplicationModelsViewModelsQueryBuilderQuery {
    return NKMRTDApplicationModelsViewModelsQueryBuilderQueryFromJSONTyped(json, false);
}

export function NKMRTDApplicationModelsViewModelsQueryBuilderQueryFromJSONTyped(json: any, ignoreDiscriminator: boolean): NKMRTDApplicationModelsViewModelsQueryBuilderQuery {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'condition': !exists(json, 'condition') ? undefined : NKMRTDApplicationEnumsConditionFromJSON(json['condition']),
        'not': !exists(json, 'not') ? undefined : json['not'],
        'id': !exists(json, 'id') ? undefined : json['id'],
        'fieldName': !exists(json, 'fieldName') ? undefined : json['fieldName'],
        'operator': !exists(json, 'operator') ? undefined : NKMRTDApplicationEnumsOperatorFromJSON(json['operator']),
        'type': !exists(json, 'type') ? undefined : NKMRTDApplicationEnumsControlTypeFromJSON(json['type']),
        'rules': !exists(json, 'rules') ? undefined : (json['rules'] === null ? null : (json['rules'] as Array<any>).map(NKMRTDApplicationModelsViewModelsQueryBuilderQueryFromJSON)),
        'values': !exists(json, 'values') ? undefined : (json['values'] === null ? null : (json['values'] as Array<any>).map(NKMRTDApplicationModelsViewModelsQueryValuesFromJSON)),
    };
}

export function NKMRTDApplicationModelsViewModelsQueryBuilderQueryToJSON(value?: NKMRTDApplicationModelsViewModelsQueryBuilderQuery | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'condition': NKMRTDApplicationEnumsConditionToJSON(value.condition),
        'not': value.not,
        'id': value.id,
        'fieldName': value.fieldName,
        'operator': NKMRTDApplicationEnumsOperatorToJSON(value.operator),
        'type': NKMRTDApplicationEnumsControlTypeToJSON(value.type),
        'rules': value.rules === undefined ? undefined : (value.rules === null ? null : (value.rules as Array<any>).map(NKMRTDApplicationModelsViewModelsQueryBuilderQueryToJSON)),
        'values': value.values === undefined ? undefined : (value.values === null ? null : (value.values as Array<any>).map(NKMRTDApplicationModelsViewModelsQueryValuesToJSON)),
    };
}


