/* tslint:disable */
/* eslint-disable */
/**
 * NKM RTD CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NKMRTDCampaignEditorApplicationCommonMessagesEnumsSegmentationType,
    NKMRTDCampaignEditorApplicationCommonMessagesEnumsSegmentationTypeFromJSON,
    NKMRTDCampaignEditorApplicationCommonMessagesEnumsSegmentationTypeFromJSONTyped,
    NKMRTDCampaignEditorApplicationCommonMessagesEnumsSegmentationTypeToJSON,
    NKMRTDCampaignEditorApplicationCommonMessagesViewModelsQueryBuilderQuery,
    NKMRTDCampaignEditorApplicationCommonMessagesViewModelsQueryBuilderQueryFromJSON,
    NKMRTDCampaignEditorApplicationCommonMessagesViewModelsQueryBuilderQueryFromJSONTyped,
    NKMRTDCampaignEditorApplicationCommonMessagesViewModelsQueryBuilderQueryToJSON,
    NKMRTDCampaignEditorApplicationCommonMessagesViewModelsSegmentConditionVm,
    NKMRTDCampaignEditorApplicationCommonMessagesViewModelsSegmentConditionVmFromJSON,
    NKMRTDCampaignEditorApplicationCommonMessagesViewModelsSegmentConditionVmFromJSONTyped,
    NKMRTDCampaignEditorApplicationCommonMessagesViewModelsSegmentConditionVmToJSON,
} from './';

/**
 * 
 * @export
 * @interface NKMRTDCampaignEditorApplicationSegmentationsCommandsUpdateSegmentationUpdateSegmentationCommand
 */
export interface NKMRTDCampaignEditorApplicationSegmentationsCommandsUpdateSegmentationUpdateSegmentationCommand {
    /**
     * 
     * @type {number}
     * @memberof NKMRTDCampaignEditorApplicationSegmentationsCommandsUpdateSegmentationUpdateSegmentationCommand
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof NKMRTDCampaignEditorApplicationSegmentationsCommandsUpdateSegmentationUpdateSegmentationCommand
     */
    name?: string | null;
    /**
     * 
     * @type {NKMRTDCampaignEditorApplicationCommonMessagesEnumsSegmentationType}
     * @memberof NKMRTDCampaignEditorApplicationSegmentationsCommandsUpdateSegmentationUpdateSegmentationCommand
     */
    type?: NKMRTDCampaignEditorApplicationCommonMessagesEnumsSegmentationType;
    /**
     * 
     * @type {number}
     * @memberof NKMRTDCampaignEditorApplicationSegmentationsCommandsUpdateSegmentationUpdateSegmentationCommand
     */
    segmentationCategoryId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NKMRTDCampaignEditorApplicationSegmentationsCommandsUpdateSegmentationUpdateSegmentationCommand
     */
    segmentSize?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NKMRTDCampaignEditorApplicationSegmentationsCommandsUpdateSegmentationUpdateSegmentationCommand
     */
    cumulativeIntersection?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NKMRTDCampaignEditorApplicationSegmentationsCommandsUpdateSegmentationUpdateSegmentationCommand
     */
    referenceSegmentationId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof NKMRTDCampaignEditorApplicationSegmentationsCommandsUpdateSegmentationUpdateSegmentationCommand
     */
    queryId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof NKMRTDCampaignEditorApplicationSegmentationsCommandsUpdateSegmentationUpdateSegmentationCommand
     */
    tree?: string | null;
    /**
     * 
     * @type {NKMRTDCampaignEditorApplicationCommonMessagesViewModelsQueryBuilderQuery}
     * @memberof NKMRTDCampaignEditorApplicationSegmentationsCommandsUpdateSegmentationUpdateSegmentationCommand
     */
    query?: NKMRTDCampaignEditorApplicationCommonMessagesViewModelsQueryBuilderQuery | null;
    /**
     * 
     * @type {Array<NKMRTDCampaignEditorApplicationCommonMessagesViewModelsSegmentConditionVm>}
     * @memberof NKMRTDCampaignEditorApplicationSegmentationsCommandsUpdateSegmentationUpdateSegmentationCommand
     */
    conditions?: Array<NKMRTDCampaignEditorApplicationCommonMessagesViewModelsSegmentConditionVm> | null;
}

export function NKMRTDCampaignEditorApplicationSegmentationsCommandsUpdateSegmentationUpdateSegmentationCommandFromJSON(json: any): NKMRTDCampaignEditorApplicationSegmentationsCommandsUpdateSegmentationUpdateSegmentationCommand {
    return NKMRTDCampaignEditorApplicationSegmentationsCommandsUpdateSegmentationUpdateSegmentationCommandFromJSONTyped(json, false);
}

export function NKMRTDCampaignEditorApplicationSegmentationsCommandsUpdateSegmentationUpdateSegmentationCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): NKMRTDCampaignEditorApplicationSegmentationsCommandsUpdateSegmentationUpdateSegmentationCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'type': !exists(json, 'type') ? undefined : NKMRTDCampaignEditorApplicationCommonMessagesEnumsSegmentationTypeFromJSON(json['type']),
        'segmentationCategoryId': !exists(json, 'segmentationCategoryId') ? undefined : json['segmentationCategoryId'],
        'segmentSize': !exists(json, 'segmentSize') ? undefined : json['segmentSize'],
        'cumulativeIntersection': !exists(json, 'cumulativeIntersection') ? undefined : json['cumulativeIntersection'],
        'referenceSegmentationId': !exists(json, 'referenceSegmentationId') ? undefined : json['referenceSegmentationId'],
        'queryId': !exists(json, 'queryId') ? undefined : json['queryId'],
        'tree': !exists(json, 'tree') ? undefined : json['tree'],
        'query': !exists(json, 'query') ? undefined : NKMRTDCampaignEditorApplicationCommonMessagesViewModelsQueryBuilderQueryFromJSON(json['query']),
        'conditions': !exists(json, 'conditions') ? undefined : (json['conditions'] === null ? null : (json['conditions'] as Array<any>).map(NKMRTDCampaignEditorApplicationCommonMessagesViewModelsSegmentConditionVmFromJSON)),
    };
}

export function NKMRTDCampaignEditorApplicationSegmentationsCommandsUpdateSegmentationUpdateSegmentationCommandToJSON(value?: NKMRTDCampaignEditorApplicationSegmentationsCommandsUpdateSegmentationUpdateSegmentationCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'type': NKMRTDCampaignEditorApplicationCommonMessagesEnumsSegmentationTypeToJSON(value.type),
        'segmentationCategoryId': value.segmentationCategoryId,
        'segmentSize': value.segmentSize,
        'cumulativeIntersection': value.cumulativeIntersection,
        'referenceSegmentationId': value.referenceSegmentationId,
        'queryId': value.queryId,
        'tree': value.tree,
        'query': NKMRTDCampaignEditorApplicationCommonMessagesViewModelsQueryBuilderQueryToJSON(value.query),
        'conditions': value.conditions === undefined ? undefined : (value.conditions === null ? null : (value.conditions as Array<any>).map(NKMRTDCampaignEditorApplicationCommonMessagesViewModelsSegmentConditionVmToJSON)),
    };
}


