/* tslint:disable */
/* eslint-disable */
/**
 * Optima CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OptimaCampaignEditorApplicationModelsAdminInt32EntityCreatedVm
 */
export interface OptimaCampaignEditorApplicationModelsAdminInt32EntityCreatedVm {
    /**
     * 
     * @type {number}
     * @memberof OptimaCampaignEditorApplicationModelsAdminInt32EntityCreatedVm
     */
    id?: number;
}

export function OptimaCampaignEditorApplicationModelsAdminInt32EntityCreatedVmFromJSON(json: any): OptimaCampaignEditorApplicationModelsAdminInt32EntityCreatedVm {
    return OptimaCampaignEditorApplicationModelsAdminInt32EntityCreatedVmFromJSONTyped(json, false);
}

export function OptimaCampaignEditorApplicationModelsAdminInt32EntityCreatedVmFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptimaCampaignEditorApplicationModelsAdminInt32EntityCreatedVm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function OptimaCampaignEditorApplicationModelsAdminInt32EntityCreatedVmToJSON(value?: OptimaCampaignEditorApplicationModelsAdminInt32EntityCreatedVm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}


