/* tslint:disable */
/* eslint-disable */
/**
 * Optima CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OptimaCampaignEditorApplicationCommonMessagesRequestsEmailChannelSettingsDto,
    OptimaCampaignEditorApplicationCommonMessagesRequestsEmailChannelSettingsDtoFromJSON,
    OptimaCampaignEditorApplicationCommonMessagesRequestsEmailChannelSettingsDtoFromJSONTyped,
    OptimaCampaignEditorApplicationCommonMessagesRequestsEmailChannelSettingsDtoToJSON,
    OptimaCampaignEditorApplicationCommonMessagesRequestsTimingDto,
    OptimaCampaignEditorApplicationCommonMessagesRequestsTimingDtoFromJSON,
    OptimaCampaignEditorApplicationCommonMessagesRequestsTimingDtoFromJSONTyped,
    OptimaCampaignEditorApplicationCommonMessagesRequestsTimingDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface OptimaCampaignEditorApplicationCampaignsCommandsCreateCampaignSettingsCreateCampaignSettingsCommand
 */
export interface OptimaCampaignEditorApplicationCampaignsCommandsCreateCampaignSettingsCreateCampaignSettingsCommand {
    /**
     * 
     * @type {string}
     * @memberof OptimaCampaignEditorApplicationCampaignsCommandsCreateCampaignSettingsCreateCampaignSettingsCommand
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OptimaCampaignEditorApplicationCampaignsCommandsCreateCampaignSettingsCreateCampaignSettingsCommand
     */
    description?: string | null;
    /**
     * 
     * @type {number}
     * @memberof OptimaCampaignEditorApplicationCampaignsCommandsCreateCampaignSettingsCreateCampaignSettingsCommand
     */
    channelId?: number;
    /**
     * 
     * @type {number}
     * @memberof OptimaCampaignEditorApplicationCampaignsCommandsCreateCampaignSettingsCreateCampaignSettingsCommand
     */
    productId?: number;
    /**
     * 
     * @type {number}
     * @memberof OptimaCampaignEditorApplicationCampaignsCommandsCreateCampaignSettingsCreateCampaignSettingsCommand
     */
    requestorId?: number;
    /**
     * 
     * @type {number}
     * @memberof OptimaCampaignEditorApplicationCampaignsCommandsCreateCampaignSettingsCreateCampaignSettingsCommand
     */
    responsibleId?: number;
    /**
     * 
     * @type {OptimaCampaignEditorApplicationCommonMessagesRequestsTimingDto}
     * @memberof OptimaCampaignEditorApplicationCampaignsCommandsCreateCampaignSettingsCreateCampaignSettingsCommand
     */
    timing?: OptimaCampaignEditorApplicationCommonMessagesRequestsTimingDto | null;
    /**
     * 
     * @type {OptimaCampaignEditorApplicationCommonMessagesRequestsEmailChannelSettingsDto}
     * @memberof OptimaCampaignEditorApplicationCampaignsCommandsCreateCampaignSettingsCreateCampaignSettingsCommand
     */
    emailChannelSettings?: OptimaCampaignEditorApplicationCommonMessagesRequestsEmailChannelSettingsDto | null;
}

export function OptimaCampaignEditorApplicationCampaignsCommandsCreateCampaignSettingsCreateCampaignSettingsCommandFromJSON(json: any): OptimaCampaignEditorApplicationCampaignsCommandsCreateCampaignSettingsCreateCampaignSettingsCommand {
    return OptimaCampaignEditorApplicationCampaignsCommandsCreateCampaignSettingsCreateCampaignSettingsCommandFromJSONTyped(json, false);
}

export function OptimaCampaignEditorApplicationCampaignsCommandsCreateCampaignSettingsCreateCampaignSettingsCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptimaCampaignEditorApplicationCampaignsCommandsCreateCampaignSettingsCreateCampaignSettingsCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'channelId': !exists(json, 'channelId') ? undefined : json['channelId'],
        'productId': !exists(json, 'productId') ? undefined : json['productId'],
        'requestorId': !exists(json, 'requestorId') ? undefined : json['requestorId'],
        'responsibleId': !exists(json, 'responsibleId') ? undefined : json['responsibleId'],
        'timing': !exists(json, 'timing') ? undefined : OptimaCampaignEditorApplicationCommonMessagesRequestsTimingDtoFromJSON(json['timing']),
        'emailChannelSettings': !exists(json, 'emailChannelSettings') ? undefined : OptimaCampaignEditorApplicationCommonMessagesRequestsEmailChannelSettingsDtoFromJSON(json['emailChannelSettings']),
    };
}

export function OptimaCampaignEditorApplicationCampaignsCommandsCreateCampaignSettingsCreateCampaignSettingsCommandToJSON(value?: OptimaCampaignEditorApplicationCampaignsCommandsCreateCampaignSettingsCreateCampaignSettingsCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'description': value.description,
        'channelId': value.channelId,
        'productId': value.productId,
        'requestorId': value.requestorId,
        'responsibleId': value.responsibleId,
        'timing': OptimaCampaignEditorApplicationCommonMessagesRequestsTimingDtoToJSON(value.timing),
        'emailChannelSettings': OptimaCampaignEditorApplicationCommonMessagesRequestsEmailChannelSettingsDtoToJSON(value.emailChannelSettings),
    };
}


