/* tslint:disable */
/* eslint-disable */
/**
 * Optima CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OptimaCampaignEditorApplicationCommonMessagesViewModelsSelectOptionVm
 */
export interface OptimaCampaignEditorApplicationCommonMessagesViewModelsSelectOptionVm {
    /**
     * 
     * @type {number}
     * @memberof OptimaCampaignEditorApplicationCommonMessagesViewModelsSelectOptionVm
     */
    value?: number;
    /**
     * 
     * @type {string}
     * @memberof OptimaCampaignEditorApplicationCommonMessagesViewModelsSelectOptionVm
     */
    text?: string | null;
}

export function OptimaCampaignEditorApplicationCommonMessagesViewModelsSelectOptionVmFromJSON(json: any): OptimaCampaignEditorApplicationCommonMessagesViewModelsSelectOptionVm {
    return OptimaCampaignEditorApplicationCommonMessagesViewModelsSelectOptionVmFromJSONTyped(json, false);
}

export function OptimaCampaignEditorApplicationCommonMessagesViewModelsSelectOptionVmFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptimaCampaignEditorApplicationCommonMessagesViewModelsSelectOptionVm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'value': !exists(json, 'value') ? undefined : json['value'],
        'text': !exists(json, 'text') ? undefined : json['text'],
    };
}

export function OptimaCampaignEditorApplicationCommonMessagesViewModelsSelectOptionVmToJSON(value?: OptimaCampaignEditorApplicationCommonMessagesViewModelsSelectOptionVm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'value': value.value,
        'text': value.text,
    };
}


