/* tslint:disable */
/* eslint-disable */
/**
 * Optima CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OptimaCampaignEditorApplicationModelsSegmentationQueryBuilderField,
    OptimaCampaignEditorApplicationModelsSegmentationQueryBuilderFieldFromJSON,
    OptimaCampaignEditorApplicationModelsSegmentationQueryBuilderFieldFromJSONTyped,
    OptimaCampaignEditorApplicationModelsSegmentationQueryBuilderFieldToJSON,
} from './';

/**
 * 
 * @export
 * @interface OptimaCampaignEditorApplicationModelsSegmentationQueryBuilderFieldConfig
 */
export interface OptimaCampaignEditorApplicationModelsSegmentationQueryBuilderFieldConfig {
    /**
     * 
     * @type {Array<OptimaCampaignEditorApplicationModelsSegmentationQueryBuilderField>}
     * @memberof OptimaCampaignEditorApplicationModelsSegmentationQueryBuilderFieldConfig
     */
    readonly fields?: Array<OptimaCampaignEditorApplicationModelsSegmentationQueryBuilderField> | null;
}

export function OptimaCampaignEditorApplicationModelsSegmentationQueryBuilderFieldConfigFromJSON(json: any): OptimaCampaignEditorApplicationModelsSegmentationQueryBuilderFieldConfig {
    return OptimaCampaignEditorApplicationModelsSegmentationQueryBuilderFieldConfigFromJSONTyped(json, false);
}

export function OptimaCampaignEditorApplicationModelsSegmentationQueryBuilderFieldConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptimaCampaignEditorApplicationModelsSegmentationQueryBuilderFieldConfig {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fields': !exists(json, 'fields') ? undefined : (json['fields'] === null ? null : (json['fields'] as Array<any>).map(OptimaCampaignEditorApplicationModelsSegmentationQueryBuilderFieldFromJSON)),
    };
}

export function OptimaCampaignEditorApplicationModelsSegmentationQueryBuilderFieldConfigToJSON(value?: OptimaCampaignEditorApplicationModelsSegmentationQueryBuilderFieldConfig | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


