/* tslint:disable */
/* eslint-disable */
/**
 * Optima CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OptimaCampaignEditorApplicationCommonMessagesEnumsSegmentationType,
    OptimaCampaignEditorApplicationCommonMessagesEnumsSegmentationTypeFromJSON,
    OptimaCampaignEditorApplicationCommonMessagesEnumsSegmentationTypeFromJSONTyped,
    OptimaCampaignEditorApplicationCommonMessagesEnumsSegmentationTypeToJSON,
    OptimaCampaignEditorApplicationCommonMessagesRequestsSegmentationQueryDto,
    OptimaCampaignEditorApplicationCommonMessagesRequestsSegmentationQueryDtoFromJSON,
    OptimaCampaignEditorApplicationCommonMessagesRequestsSegmentationQueryDtoFromJSONTyped,
    OptimaCampaignEditorApplicationCommonMessagesRequestsSegmentationQueryDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface OptimaCampaignEditorApplicationCommonMessagesRequestsDiscountSegmentDto
 */
export interface OptimaCampaignEditorApplicationCommonMessagesRequestsDiscountSegmentDto {
    /**
     * 
     * @type {number}
     * @memberof OptimaCampaignEditorApplicationCommonMessagesRequestsDiscountSegmentDto
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof OptimaCampaignEditorApplicationCommonMessagesRequestsDiscountSegmentDto
     */
    name?: string | null;
    /**
     * 
     * @type {OptimaCampaignEditorApplicationCommonMessagesEnumsSegmentationType}
     * @memberof OptimaCampaignEditorApplicationCommonMessagesRequestsDiscountSegmentDto
     */
    type?: OptimaCampaignEditorApplicationCommonMessagesEnumsSegmentationType;
    /**
     * 
     * @type {number}
     * @memberof OptimaCampaignEditorApplicationCommonMessagesRequestsDiscountSegmentDto
     */
    segmentationCategoryId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof OptimaCampaignEditorApplicationCommonMessagesRequestsDiscountSegmentDto
     */
    referenceSegmentationId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof OptimaCampaignEditorApplicationCommonMessagesRequestsDiscountSegmentDto
     */
    segmentSize?: number | null;
    /**
     * 
     * @type {number}
     * @memberof OptimaCampaignEditorApplicationCommonMessagesRequestsDiscountSegmentDto
     */
    cumulativeIntersection?: number | null;
    /**
     * 
     * @type {number}
     * @memberof OptimaCampaignEditorApplicationCommonMessagesRequestsDiscountSegmentDto
     */
    businessPartnerCount?: number;
    /**
     * 
     * @type {OptimaCampaignEditorApplicationCommonMessagesRequestsSegmentationQueryDto}
     * @memberof OptimaCampaignEditorApplicationCommonMessagesRequestsDiscountSegmentDto
     */
    query?: OptimaCampaignEditorApplicationCommonMessagesRequestsSegmentationQueryDto | null;
}

export function OptimaCampaignEditorApplicationCommonMessagesRequestsDiscountSegmentDtoFromJSON(json: any): OptimaCampaignEditorApplicationCommonMessagesRequestsDiscountSegmentDto {
    return OptimaCampaignEditorApplicationCommonMessagesRequestsDiscountSegmentDtoFromJSONTyped(json, false);
}

export function OptimaCampaignEditorApplicationCommonMessagesRequestsDiscountSegmentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptimaCampaignEditorApplicationCommonMessagesRequestsDiscountSegmentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'type': !exists(json, 'type') ? undefined : OptimaCampaignEditorApplicationCommonMessagesEnumsSegmentationTypeFromJSON(json['type']),
        'segmentationCategoryId': !exists(json, 'segmentationCategoryId') ? undefined : json['segmentationCategoryId'],
        'referenceSegmentationId': !exists(json, 'referenceSegmentationId') ? undefined : json['referenceSegmentationId'],
        'segmentSize': !exists(json, 'segmentSize') ? undefined : json['segmentSize'],
        'cumulativeIntersection': !exists(json, 'cumulativeIntersection') ? undefined : json['cumulativeIntersection'],
        'businessPartnerCount': !exists(json, 'businessPartnerCount') ? undefined : json['businessPartnerCount'],
        'query': !exists(json, 'query') ? undefined : OptimaCampaignEditorApplicationCommonMessagesRequestsSegmentationQueryDtoFromJSON(json['query']),
    };
}

export function OptimaCampaignEditorApplicationCommonMessagesRequestsDiscountSegmentDtoToJSON(value?: OptimaCampaignEditorApplicationCommonMessagesRequestsDiscountSegmentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'type': OptimaCampaignEditorApplicationCommonMessagesEnumsSegmentationTypeToJSON(value.type),
        'segmentationCategoryId': value.segmentationCategoryId,
        'referenceSegmentationId': value.referenceSegmentationId,
        'segmentSize': value.segmentSize,
        'cumulativeIntersection': value.cumulativeIntersection,
        'businessPartnerCount': value.businessPartnerCount,
        'query': OptimaCampaignEditorApplicationCommonMessagesRequestsSegmentationQueryDtoToJSON(value.query),
    };
}


