/* tslint:disable */
/* eslint-disable */
/**
 * Optima CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OptimaCampaignEditorApplicationCommonMessagesEnumsSegmentationType,
    OptimaCampaignEditorApplicationCommonMessagesEnumsSegmentationTypeFromJSON,
    OptimaCampaignEditorApplicationCommonMessagesEnumsSegmentationTypeFromJSONTyped,
    OptimaCampaignEditorApplicationCommonMessagesEnumsSegmentationTypeToJSON,
    OptimaCampaignEditorApplicationCommonMessagesViewModelsQueryBuilderQuery,
    OptimaCampaignEditorApplicationCommonMessagesViewModelsQueryBuilderQueryFromJSON,
    OptimaCampaignEditorApplicationCommonMessagesViewModelsQueryBuilderQueryFromJSONTyped,
    OptimaCampaignEditorApplicationCommonMessagesViewModelsQueryBuilderQueryToJSON,
    OptimaCampaignEditorApplicationCommonMessagesViewModelsSegmentConditionVm,
    OptimaCampaignEditorApplicationCommonMessagesViewModelsSegmentConditionVmFromJSON,
    OptimaCampaignEditorApplicationCommonMessagesViewModelsSegmentConditionVmFromJSONTyped,
    OptimaCampaignEditorApplicationCommonMessagesViewModelsSegmentConditionVmToJSON,
} from './';

/**
 * 
 * @export
 * @interface OptimaCampaignEditorApplicationSegmentationsCommandsCreateSegmentationCreateSegmentationCommand
 */
export interface OptimaCampaignEditorApplicationSegmentationsCommandsCreateSegmentationCreateSegmentationCommand {
    /**
     * 
     * @type {number}
     * @memberof OptimaCampaignEditorApplicationSegmentationsCommandsCreateSegmentationCreateSegmentationCommand
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof OptimaCampaignEditorApplicationSegmentationsCommandsCreateSegmentationCreateSegmentationCommand
     */
    name?: string | null;
    /**
     * 
     * @type {OptimaCampaignEditorApplicationCommonMessagesEnumsSegmentationType}
     * @memberof OptimaCampaignEditorApplicationSegmentationsCommandsCreateSegmentationCreateSegmentationCommand
     */
    type?: OptimaCampaignEditorApplicationCommonMessagesEnumsSegmentationType;
    /**
     * 
     * @type {number}
     * @memberof OptimaCampaignEditorApplicationSegmentationsCommandsCreateSegmentationCreateSegmentationCommand
     */
    segmentationCategoryId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof OptimaCampaignEditorApplicationSegmentationsCommandsCreateSegmentationCreateSegmentationCommand
     */
    segmentSize?: number | null;
    /**
     * 
     * @type {number}
     * @memberof OptimaCampaignEditorApplicationSegmentationsCommandsCreateSegmentationCreateSegmentationCommand
     */
    cumulativeIntersection?: number | null;
    /**
     * 
     * @type {number}
     * @memberof OptimaCampaignEditorApplicationSegmentationsCommandsCreateSegmentationCreateSegmentationCommand
     */
    referenceSegmentationId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof OptimaCampaignEditorApplicationSegmentationsCommandsCreateSegmentationCreateSegmentationCommand
     */
    queryId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof OptimaCampaignEditorApplicationSegmentationsCommandsCreateSegmentationCreateSegmentationCommand
     */
    tree?: string | null;
    /**
     * 
     * @type {OptimaCampaignEditorApplicationCommonMessagesViewModelsQueryBuilderQuery}
     * @memberof OptimaCampaignEditorApplicationSegmentationsCommandsCreateSegmentationCreateSegmentationCommand
     */
    query?: OptimaCampaignEditorApplicationCommonMessagesViewModelsQueryBuilderQuery | null;
    /**
     * 
     * @type {Array<OptimaCampaignEditorApplicationCommonMessagesViewModelsSegmentConditionVm>}
     * @memberof OptimaCampaignEditorApplicationSegmentationsCommandsCreateSegmentationCreateSegmentationCommand
     */
    conditions?: Array<OptimaCampaignEditorApplicationCommonMessagesViewModelsSegmentConditionVm> | null;
}

export function OptimaCampaignEditorApplicationSegmentationsCommandsCreateSegmentationCreateSegmentationCommandFromJSON(json: any): OptimaCampaignEditorApplicationSegmentationsCommandsCreateSegmentationCreateSegmentationCommand {
    return OptimaCampaignEditorApplicationSegmentationsCommandsCreateSegmentationCreateSegmentationCommandFromJSONTyped(json, false);
}

export function OptimaCampaignEditorApplicationSegmentationsCommandsCreateSegmentationCreateSegmentationCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptimaCampaignEditorApplicationSegmentationsCommandsCreateSegmentationCreateSegmentationCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'type': !exists(json, 'type') ? undefined : OptimaCampaignEditorApplicationCommonMessagesEnumsSegmentationTypeFromJSON(json['type']),
        'segmentationCategoryId': !exists(json, 'segmentationCategoryId') ? undefined : json['segmentationCategoryId'],
        'segmentSize': !exists(json, 'segmentSize') ? undefined : json['segmentSize'],
        'cumulativeIntersection': !exists(json, 'cumulativeIntersection') ? undefined : json['cumulativeIntersection'],
        'referenceSegmentationId': !exists(json, 'referenceSegmentationId') ? undefined : json['referenceSegmentationId'],
        'queryId': !exists(json, 'queryId') ? undefined : json['queryId'],
        'tree': !exists(json, 'tree') ? undefined : json['tree'],
        'query': !exists(json, 'query') ? undefined : OptimaCampaignEditorApplicationCommonMessagesViewModelsQueryBuilderQueryFromJSON(json['query']),
        'conditions': !exists(json, 'conditions') ? undefined : (json['conditions'] === null ? null : (json['conditions'] as Array<any>).map(OptimaCampaignEditorApplicationCommonMessagesViewModelsSegmentConditionVmFromJSON)),
    };
}

export function OptimaCampaignEditorApplicationSegmentationsCommandsCreateSegmentationCreateSegmentationCommandToJSON(value?: OptimaCampaignEditorApplicationSegmentationsCommandsCreateSegmentationCreateSegmentationCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'type': OptimaCampaignEditorApplicationCommonMessagesEnumsSegmentationTypeToJSON(value.type),
        'segmentationCategoryId': value.segmentationCategoryId,
        'segmentSize': value.segmentSize,
        'cumulativeIntersection': value.cumulativeIntersection,
        'referenceSegmentationId': value.referenceSegmentationId,
        'queryId': value.queryId,
        'tree': value.tree,
        'query': OptimaCampaignEditorApplicationCommonMessagesViewModelsQueryBuilderQueryToJSON(value.query),
        'conditions': value.conditions === undefined ? undefined : (value.conditions === null ? null : (value.conditions as Array<any>).map(OptimaCampaignEditorApplicationCommonMessagesViewModelsSegmentConditionVmToJSON)),
    };
}


