/* tslint:disable */
/* eslint-disable */
/**
 * Optima CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OptimaCampaignEditorApplicationModelsAdminProfileStatus,
    OptimaCampaignEditorApplicationModelsAdminProfileStatusFromJSON,
    OptimaCampaignEditorApplicationModelsAdminProfileStatusFromJSONTyped,
    OptimaCampaignEditorApplicationModelsAdminProfileStatusToJSON,
} from './';

/**
 * 
 * @export
 * @interface OptimaCampaignEditorApplicationModelsAdminProfileDto
 */
export interface OptimaCampaignEditorApplicationModelsAdminProfileDto {
    /**
     * 
     * @type {OptimaCampaignEditorApplicationModelsAdminProfileStatus}
     * @memberof OptimaCampaignEditorApplicationModelsAdminProfileDto
     */
    status?: OptimaCampaignEditorApplicationModelsAdminProfileStatus | null;
    /**
     * 
     * @type {string}
     * @memberof OptimaCampaignEditorApplicationModelsAdminProfileDto
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OptimaCampaignEditorApplicationModelsAdminProfileDto
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OptimaCampaignEditorApplicationModelsAdminProfileDto
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OptimaCampaignEditorApplicationModelsAdminProfileDto
     */
    profilePictureId?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof OptimaCampaignEditorApplicationModelsAdminProfileDto
     */
    birthDay?: Date;
    /**
     * 
     * @type {string}
     * @memberof OptimaCampaignEditorApplicationModelsAdminProfileDto
     */
    phoneNumber?: string | null;
    /**
     * 
     * @type {number}
     * @memberof OptimaCampaignEditorApplicationModelsAdminProfileDto
     */
    companyId?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof OptimaCampaignEditorApplicationModelsAdminProfileDto
     */
    groups?: Array<number> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof OptimaCampaignEditorApplicationModelsAdminProfileDto
     */
    permissions?: Array<string> | null;
    /**
     * 
     * @type {number}
     * @memberof OptimaCampaignEditorApplicationModelsAdminProfileDto
     */
    jobDescriptionId?: number;
}

export function OptimaCampaignEditorApplicationModelsAdminProfileDtoFromJSON(json: any): OptimaCampaignEditorApplicationModelsAdminProfileDto {
    return OptimaCampaignEditorApplicationModelsAdminProfileDtoFromJSONTyped(json, false);
}

export function OptimaCampaignEditorApplicationModelsAdminProfileDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OptimaCampaignEditorApplicationModelsAdminProfileDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': !exists(json, 'status') ? undefined : OptimaCampaignEditorApplicationModelsAdminProfileStatusFromJSON(json['status']),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'userName': !exists(json, 'userName') ? undefined : json['userName'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'profilePictureId': !exists(json, 'profilePictureId') ? undefined : json['profilePictureId'],
        'birthDay': !exists(json, 'birthDay') ? undefined : (new Date(json['birthDay'])),
        'phoneNumber': !exists(json, 'phoneNumber') ? undefined : json['phoneNumber'],
        'companyId': !exists(json, 'companyId') ? undefined : json['companyId'],
        'groups': !exists(json, 'groups') ? undefined : json['groups'],
        'permissions': !exists(json, 'permissions') ? undefined : json['permissions'],
        'jobDescriptionId': !exists(json, 'jobDescriptionId') ? undefined : json['jobDescriptionId'],
    };
}

export function OptimaCampaignEditorApplicationModelsAdminProfileDtoToJSON(value?: OptimaCampaignEditorApplicationModelsAdminProfileDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': OptimaCampaignEditorApplicationModelsAdminProfileStatusToJSON(value.status),
        'name': value.name,
        'userName': value.userName,
        'email': value.email,
        'profilePictureId': value.profilePictureId,
        'birthDay': value.birthDay === undefined ? undefined : (value.birthDay.toISOString()),
        'phoneNumber': value.phoneNumber,
        'companyId': value.companyId,
        'groups': value.groups,
        'permissions': value.permissions,
        'jobDescriptionId': value.jobDescriptionId,
    };
}


