/* tslint:disable */
/* eslint-disable */
/**
 * NKM RTD CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ResendPasswordChangeLinkCommand
 */
export interface ResendPasswordChangeLinkCommand {
    /**
     * Email address that identifies the standalone user
     * @type {string}
     * @memberof ResendPasswordChangeLinkCommand
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof ResendPasswordChangeLinkCommand
     */
    captchaToken?: string | null;
}

export function ResendPasswordChangeLinkCommandFromJSON(json: any): ResendPasswordChangeLinkCommand {
    return ResendPasswordChangeLinkCommandFromJSONTyped(json, false);
}

export function ResendPasswordChangeLinkCommandFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResendPasswordChangeLinkCommand {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'captchaToken': !exists(json, 'captchaToken') ? undefined : json['captchaToken'],
    };
}

export function ResendPasswordChangeLinkCommandToJSON(value?: ResendPasswordChangeLinkCommand | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'captchaToken': value.captchaToken,
    };
}


