/* tslint:disable */
/* eslint-disable */
/**
 * NKM RTD CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    BusinessPartner,
    BusinessPartnerFromJSON,
    BusinessPartnerFromJSONTyped,
    BusinessPartnerToJSON,
    SegmentationType,
    SegmentationTypeFromJSON,
    SegmentationTypeFromJSONTyped,
    SegmentationTypeToJSON,
} from './';

/**
 * 
 * @export
 * @interface SegmentModel
 */
export interface SegmentModel {
    /**
     * 
     * @type {number}
     * @memberof SegmentModel
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SegmentModel
     */
    name?: string | null;
    /**
     * 
     * @type {SegmentationType}
     * @memberof SegmentModel
     */
    type?: SegmentationType;
    /**
     * 
     * @type {number}
     * @memberof SegmentModel
     */
    segmentationCategoryId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof SegmentModel
     */
    categoryName?: string | null;
    /**
     * 
     * @type {number}
     * @memberof SegmentModel
     */
    segmentSize?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SegmentModel
     */
    cumulativeIntersection?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SegmentModel
     */
    referenceSegmentationId?: number | null;
    /**
     * 
     * @type {number}
     * @memberof SegmentModel
     */
    createdBy?: number;
    /**
     * 
     * @type {Date}
     * @memberof SegmentModel
     */
    createdDate?: Date;
    /**
     * 
     * @type {Array<BusinessPartner>}
     * @memberof SegmentModel
     */
    businessPartners?: Array<BusinessPartner> | null;
}

export function SegmentModelFromJSON(json: any): SegmentModel {
    return SegmentModelFromJSONTyped(json, false);
}

export function SegmentModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SegmentModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'type': !exists(json, 'type') ? undefined : SegmentationTypeFromJSON(json['type']),
        'segmentationCategoryId': !exists(json, 'segmentationCategoryId') ? undefined : json['segmentationCategoryId'],
        'categoryName': !exists(json, 'categoryName') ? undefined : json['categoryName'],
        'segmentSize': !exists(json, 'segmentSize') ? undefined : json['segmentSize'],
        'cumulativeIntersection': !exists(json, 'cumulativeIntersection') ? undefined : json['cumulativeIntersection'],
        'referenceSegmentationId': !exists(json, 'referenceSegmentationId') ? undefined : json['referenceSegmentationId'],
        'createdBy': !exists(json, 'createdBy') ? undefined : json['createdBy'],
        'createdDate': !exists(json, 'createdDate') ? undefined : (new Date(json['createdDate'])),
        'businessPartners': !exists(json, 'businessPartners') ? undefined : (json['businessPartners'] === null ? null : (json['businessPartners'] as Array<any>).map(BusinessPartnerFromJSON)),
    };
}

export function SegmentModelToJSON(value?: SegmentModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'type': SegmentationTypeToJSON(value.type),
        'segmentationCategoryId': value.segmentationCategoryId,
        'categoryName': value.categoryName,
        'segmentSize': value.segmentSize,
        'cumulativeIntersection': value.cumulativeIntersection,
        'referenceSegmentationId': value.referenceSegmentationId,
        'createdBy': value.createdBy,
        'createdDate': value.createdDate === undefined ? undefined : (value.createdDate.toISOString()),
        'businessPartners': value.businessPartners === undefined ? undefined : (value.businessPartners === null ? null : (value.businessPartners as Array<any>).map(BusinessPartnerToJSON)),
    };
}


