/* tslint:disable */
/* eslint-disable */
/**
 * NKM RTD CampaignEditor API
 * <h5>UI handler and the main responsibility carrier of the application, the two step transaction handling owner. The API defines the public interface for the UI and all the user exposed functions are routed here. The actual methods are supports basic segmentation creation and CSV upload functionality. CSV upload is supported via sharepoint. Authentication and JWT token are generated here from <b>Active Directory</b> login. The substraction of public api descriptions are on the API descriptions.</h5>
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SegmentationCategory,
    SegmentationCategoryFromJSON,
    SegmentationCategoryFromJSONTyped,
    SegmentationCategoryToJSON,
} from './';

/**
 * 
 * @export
 * @interface SegmentationCategoryPaginatedSearchResponse
 */
export interface SegmentationCategoryPaginatedSearchResponse {
    /**
     * 
     * @type {Array<SegmentationCategory>}
     * @memberof SegmentationCategoryPaginatedSearchResponse
     */
    items?: Array<SegmentationCategory> | null;
    /**
     * 
     * @type {number}
     * @memberof SegmentationCategoryPaginatedSearchResponse
     */
    totalCount?: number;
    /**
     * 
     * @type {number}
     * @memberof SegmentationCategoryPaginatedSearchResponse
     */
    from?: number;
    /**
     * 
     * @type {number}
     * @memberof SegmentationCategoryPaginatedSearchResponse
     */
    to?: number;
    /**
     * 
     * @type {number}
     * @memberof SegmentationCategoryPaginatedSearchResponse
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof SegmentationCategoryPaginatedSearchResponse
     */
    pageSize?: number;
}

export function SegmentationCategoryPaginatedSearchResponseFromJSON(json: any): SegmentationCategoryPaginatedSearchResponse {
    return SegmentationCategoryPaginatedSearchResponseFromJSONTyped(json, false);
}

export function SegmentationCategoryPaginatedSearchResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SegmentationCategoryPaginatedSearchResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'items': !exists(json, 'items') ? undefined : (json['items'] === null ? null : (json['items'] as Array<any>).map(SegmentationCategoryFromJSON)),
        'totalCount': !exists(json, 'totalCount') ? undefined : json['totalCount'],
        'from': !exists(json, 'from') ? undefined : json['from'],
        'to': !exists(json, 'to') ? undefined : json['to'],
        'page': !exists(json, 'page') ? undefined : json['page'],
        'pageSize': !exists(json, 'pageSize') ? undefined : json['pageSize'],
    };
}

export function SegmentationCategoryPaginatedSearchResponseToJSON(value?: SegmentationCategoryPaginatedSearchResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'items': value.items === undefined ? undefined : (value.items === null ? null : (value.items as Array<any>).map(SegmentationCategoryToJSON)),
        'totalCount': value.totalCount,
        'from': value.from,
        'to': value.to,
        'page': value.page,
        'pageSize': value.pageSize,
    };
}


