/* tslint:disable */
/* eslint-disable */
/**
 * NKM PKM Coupon Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CashierVm
 */
export interface CashierVm {
    /**
     * 
     * @type {number}
     * @memberof CashierVm
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof CashierVm
     */
    cashierId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CashierVm
     */
    digitalStampId?: string | null;
}

export function CashierVmFromJSON(json: any): CashierVm {
    return CashierVmFromJSONTyped(json, false);
}

export function CashierVmFromJSONTyped(json: any, ignoreDiscriminator: boolean): CashierVm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'cashierId': !exists(json, 'cashierId') ? undefined : json['cashierId'],
        'digitalStampId': !exists(json, 'digitalStampId') ? undefined : json['digitalStampId'],
    };
}

export function CashierVmToJSON(value?: CashierVm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'cashierId': value.cashierId,
        'digitalStampId': value.digitalStampId,
    };
}


