export enum ColumnStorageName {
  COUPON_CAMPAIGN_WAITING = 'coupon-campaign-waiting-columns',
  COUPON_CAMPAIGN_ACCEPTED = 'coupon-campaign-accepted-columns',
  COUPON_CAMPAIGN_CLOSED = 'coupon-campaign-closed-columns',
  COUPON_CAMPAIGN_CREATED = 'coupon-campaign-created-columns',
  COUPON_CAMPAIGN_ALL = 'coupon-campaign-all-columns',
  PARTNER = 'partner-columns',
  NEWSLETTER = 'newsletter-columns',
  USER_ACCESS_NKM = 'user-access-nkm-columns',
  USER_ACCES_PARTNER = 'user-access-partner-columns',
  BP_HISTORY = 'bp-history-columns',
  PERMISSION = 'permission-columns',
  SEGMENTATION = 'segmentation-columns',
  PROFILES = 'profiles-columns',
  CAMPAIGN_COMPANY = 'campaign-company-columns',
  CAMPAIGN_PARTNER = 'campaign-partner-columns',
  COMPANIES = 'company-columns',
  GROUPS = 'groups-columns',
  GROUP_PROFILES = 'group-profile-columns',
  JOB_ROLES = 'job-role-columns'
}
